In [135]:
import pandas as pd
import numpy as np

In [221]:
URL = r"D:\UM internship\Bird Strike\birdstrike_filterspecies.csv"
birdspecies_filter = pd.read_csv(URL)
birdspecies_filter.head()

,Unnamed: 0,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
0,0,KANSAS CITY INTL,< 1000 ft,MD-80,11 to 100,54,None,1/2/2000,No damage,2.0,...,False,NaN,Large,No Cloud,Canada goose,N,0,350,0,No
1,1,CINCINNATI MUNI ARPT-LUNKEN FIELD,< 1000 ft,CITATION II,1,1,None,1/2/2000,No damage,2.0,...,False,NaN,Small,Overcast,Unknown bird - small,N,0,0,0,No
2,2,MIAMI INTL,> 1000 ft,DA-2000,1,1,None,1/2/2000,No damage,2.0,...,False,NaN,Medium,No Cloud,Unknown bird - medium,Y,0,2000,0,No
3,3,SOUTHWEST FLORIDA INTL ARPT,< 1000 ft,HAWKER 800,1,1,None,1/2/2000,Caused damage,2.0,...,False,SUSPECT GULL. HEARD THUMP ON APCH BUT NO ABNRM...,Medium,No Cloud,Unknown bird - medium,Y,120273,200,0,No
4,4,NASHVILLE INTL,< 1000 ft,B-737-400,1,1,None,1/3/2000,No damage,2.0,...,False,NaN,Small,Some Cloud,Unknown bird - small,Y,0,800,0,Yes

In [222]:
birdspecies_filter.drop('Unnamed: 0', axis = 1, inplace = True)

In [223]:
birdspecies_filter.head()

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
0,KANSAS CITY INTL,< 1000 ft,MD-80,11 to 100,54,None,1/2/2000,No damage,2.0,TRANS WORLD AIRLINES,...,False,NaN,Large,No Cloud,Canada goose,N,0,350,0,No
1,CINCINNATI MUNI ARPT-LUNKEN FIELD,< 1000 ft,CITATION II,1,1,None,1/2/2000,No damage,2.0,BUSINESS,...,False,NaN,Small,Overcast,Unknown bird - small,N,0,0,0,No
2,MIAMI INTL,> 1000 ft,DA-2000,1,1,None,1/2/2000,No damage,2.0,BUSINESS,...,False,NaN,Medium,No Cloud,Unknown bird - medium,Y,0,2000,0,No
3,SOUTHWEST FLORIDA INTL ARPT,< 1000 ft,HAWKER 800,1,1,None,1/2/2000,Caused damage,2.0,BUSINESS,...,False,SUSPECT GULL. HEARD THUMP ON APCH BUT NO ABNRM...,Medium,No Cloud,Unknown bird - medium,Y,120273,200,0,No
4,NASHVILLE INTL,< 1000 ft,B-737-400,1,1,None,1/3/2000,No damage,2.0,US AIRWAYS*,...,False,NaN,Small,Some Cloud,Unknown bird - small,Y,0,800,0,Yes

In [224]:
birdspecies_filter['Altitude bin'].unique

<bound method Series.unique of 0        < 1000 ft
1        < 1000 ft
2        > 1000 ft
3        < 1000 ft
4        < 1000 ft
           ...
25198    < 1000 ft
25199    > 1000 ft
25200    < 1000 ft
25201    < 1000 ft
25202    < 1000 ft
Name: Altitude bin, Length: 25203, dtype: object>

In [225]:
birdspecies_filter.shape

(25203, 24)

In [226]:
birdspecies_filter.describe()

,Wildlife: Number Struck Actual,Aircraft: Number of engines?,Cost: Total $,Feet above ground,Number of people injured
count,25203.000000,24978.000000,2.520300e+04,25203.000000,25203.000000
mean,2.713526,2.005765,4.846457e+03,805.499345,0.000754
std,12.882044,0.363550,9.385988e+04,1745.988738,0.045852
min,1.000000,1.000000,0.000000e+00,0.000000,0.000000
25%,1.000000,2.000000,0.000000e+00,0.000000,0.000000
50%,1.000000,2.000000,0.000000e+00,50.000000,0.000000
75%,1.000000,2.000000,0.000000e+00,700.000000,0.000000
max,942.000000,4.000000,5.704387e+06,18000.000000,6.000000

In [227]:
birdspecies_filter.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25203 entries, 0 to 25202
Data columns (total 24 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Airport: Name                            25203 non-null  object
 1   Altitude bin                             25203 non-null  object
 2   Aircraft: Make/Model                     25203 non-null  object
 3   Wildlife: Number struck                  25203 non-null  object
 4   Wildlife: Number Struck Actual           25203 non-null  int64
 5   Effect: Impact to flight                 25203 non-null  object
 6   FlightDate                               25203 non-null  object
 7   Effect: Indicated Damage                 25203 non-null  object
 8   Aircraft: Number of engines?             24978 non-null  float64
 9   Aircraft: Airline/Operator               25203 non-null  object
 10  Origin State                             24754 non-null  object
 11  When: Phase of flight                    25203 non-null  object
 12  Conditions: Precipitation                25203 non-null  object
 13  Remains of wildlife collected?           25203 non-null  bool
 14  Remains of wildlife sent to Smithsonian  25203 non-null  bool
 15  Remarks                                  20451 non-null  object
 16  Wildlife: Size                           25203 non-null  object
 17  Conditions: Sky                          25203 non-null  object
 18  Wildlife: Species                        25203 non-null  object
 19  Pilot warned of birds or wildlife?       25203 non-null  object
 20  Cost: Total $                            25203 non-null  int64
 21  Feet above ground                        25203 non-null  int64
 22  Number of people injured                 25203 non-null  int64
 23  Is Aircraft Large?                       25203 non-null  object
dtypes: bool(2), float64(1), int64(4), object(17)
memory usage: 4.3+ MB

In [230]:
birdspecies_filter['Origin State'].isnull().sum()

449

In [231]:
birdspecies_filter['Origin State'].value_counts()

California                   2478
Texas                        2431
Florida                      2027
New York                     1304
Illinois                      999
Pennsylvania                  969
Missouri                      950
Kentucky                      806
Ohio                          761
Hawaii                        716
Michigan                      663
Colorado                      660
Tennessee                     651
North Carolina                649
New Jersey                    589
Georgia                       504
Utah                          489
DC                            432
Maryland                      427
Oregon                        388
Louisiana                     380
Nebraska                      367
Arizona                       349
Massachusetts                 348
Minnesota                     347
Indiana                       339
Washington                    327
Alabama                       294
Virginia                      293
Wisconsin                     280
Connecticut                   245
Iowa                          227
Oklahoma                      207
Alaska                        179
Nevada                        167
South Carolina                162
Rhode Island                  125
New Hampshire                 119
Arkansas                      116
Mississippi                   112
Kansas                         97
New Mexico                     90
North Dakota                   87
Prince Edward Island           83
West Virginia                  73
Puerto Rico                    70
Idaho                          67
South Dakota                   59
Montana                        43
Maine                          40
Vermont                        36
Wyoming                        34
Virgin Islands                 31
Delaware                       27
Ontario                        14
British Columbia               12
Quebec                          9
Alberta                         3
Newfoundland and Labrador       2
Saskatchewan                    1
Name: Origin State, dtype: int64

In [232]:
birdspecies_filter.isnull().sum()

Airport: Name                                 0
Altitude bin                                  0
Aircraft: Make/Model                          0
Wildlife: Number struck                       0
Wildlife: Number Struck Actual                0
Effect: Impact to flight                      0
FlightDate                                    0
Effect: Indicated Damage                      0
Aircraft: Number of engines?                225
Aircraft: Airline/Operator                    0
Origin State                                449
When: Phase of flight                         0
Conditions: Precipitation                     0
Remains of wildlife collected?                0
Remains of wildlife sent to Smithsonian       0
Remarks                                    4752
Wildlife: Size                                0
Conditions: Sky                               0
Wildlife: Species                             0
Pilot warned of birds or wildlife?            0
Cost: Total $                                 0
Feet above ground                             0
Number of people injured                      0
Is Aircraft Large?                            0
dtype: int64

In [233]:
birdspecies_filter['Conditions: Sky'].unique()

array(['No Cloud', 'Overcast', 'Some Cloud'], dtype=object)

In [234]:
percentage_missing = (225 / len(birdspecies_filter)) * 100
percentage_missing

0.8927508629925008

In [235]:
birdspecies_filter['Conditions: Precipitation'].value_counts()

None               23209
Rain                1341
Fog                  469
Snow                  86
Fog, Rain             85
Rain, Snow             6
Fog, Snow              4
Fog, Rain, Snow        3
Name: Conditions: Precipitation, dtype: int64

In [236]:
birdspecies_filter['Aircraft: Number of engines?'].unique()

array([ 2.,  3.,  1., nan,  4.])

In [237]:
total_strike_count = birdspecies_filter.shape[0]
total_strike_count

25203

In [238]:
birdspecies_filter['Aircraft: Number of engines?']

0        2.0
1        2.0
2        2.0
3        2.0
4        2.0
        ...
25198    2.0
25199    2.0
25200    2.0
25201    2.0
25202    2.0
Name: Aircraft: Number of engines?, Length: 25203, dtype: float64

In [199]:
filtered_df = birdspecies_filter[birdspecies_filter['Aircraft: Number of engines?'] == 2]



# Assuming your DataFrame is named birdspecies_filter

# Step 1: Filter the dataset for rows where 'Damage Location' contains the substring 'engine'
filtered_df2 = filtered_df[filtered_df['Remarks'].str.contains('eng', case=False, na=False)]

# Step 2: Optionally, select specific columns of interest
# result = filtered_df[['Column1', 'Column2']]  # replace 'Column1' and 'Column2' with actual column names

# Display the filtered result
filtered_df2[['Aircraft: Number of engines?', 'Remarks']]

,Aircraft: Number of engines?,Remarks
3,2.0,SUSPECT GULL. HEARD THUMP ON APCH BUT NO ABNRM...
5,2.0,PREC. LDG. ENG SHUT DOWN. INGESTION. ENG VIBRA...
6,2.0,"FLT 128 ENCOUNTERED 15-20 BIRDS. AT 1000 FT, ..."
14,2.0,FLEW THRU A FLOCK OF ABOUT 30 BIRDS. INGESTED ...
29,2.0,"JUST OUTSIDE OF WILLT ON VISUAL APCH, WE FLEW ..."
...,...,...
25188,2.0,ID BY SMITHSONIAN. MULTIPLE SPECIES. SAMPLE 1 ...
25189,2.0,ID BY SMITHSONIAN. BIRD HIT FUSELAGE THEN WENT...
25190,2.0,ID BY SMITHSONIAN. HIT 3 BIRDS AND RETD TO LAN...
25191,2.0,#2 ENG INGESTED A BIRD.
25196,2.0,EARLY REPORT SAID POSSIBLE DMG TO RADOME AND D...

In [155]:
filtered_df2[['Aircraft: Number of engines?', 'Remarks']]

,Aircraft: Number of engines?,Remarks
1341,2.0,ENGINE WAS CHANGED AND DENTED COWLING WAS REPL...
1463,2.0,RETD TO ARPT AFTER REPORTING A BIRDSTRIKE SHOR...
2095,2.0,FLT 657 RETD TO LAND AFTER A BIRD STRIKE. BOTH...
3351,2.0,FLEW THRU A FLOCK. NO STRIKES NOTED. POST FLT ...
3436,2.0,CREW NOTICED AN UNUSUAL VIBRATION IN ONE ENG. ...
...,...,...
24377,2.0,ID BY SMITHSONIAN. PORT AUTH RECVD A CALL FROM...
24446,2.0,NUMEROUS STRIKES ON NOSE AND INSIDE BOTH ENGIN...
24819,2.0,"ID BY SMITHSONIAN. FAA 6862, WHOLE FEATHER. BI..."
25102,2.0,BIRD SEEN PASSING IN FRONT OF A/C DURING T/D. ...
25189,2.0,ID BY SMITHSONIAN. BIRD HIT FUSELAGE THEN WENT...

In [156]:
filtered_df_engine2[['Aircraft: Number of engines?', 'Remarks']]

,Aircraft: Number of engines?,Remarks
1341,2.0,ENGINE WAS CHANGED AND DENTED COWLING WAS REPL...
1463,2.0,RETD TO ARPT AFTER REPORTING A BIRDSTRIKE SHOR...
2095,2.0,FLT 657 RETD TO LAND AFTER A BIRD STRIKE. BOTH...
3351,2.0,FLEW THRU A FLOCK. NO STRIKES NOTED. POST FLT ...
3436,2.0,CREW NOTICED AN UNUSUAL VIBRATION IN ONE ENG. ...
...,...,...
24377,2.0,ID BY SMITHSONIAN. PORT AUTH RECVD A CALL FROM...
24446,2.0,NUMEROUS STRIKES ON NOSE AND INSIDE BOTH ENGIN...
24819,2.0,"ID BY SMITHSONIAN. FAA 6862, WHOLE FEATHER. BI..."
25102,2.0,BIRD SEEN PASSING IN FRONT OF A/C DURING T/D. ...
25189,2.0,ID BY SMITHSONIAN. BIRD HIT FUSELAGE THEN WENT...

In [157]:
filtered_dfnan = birdspecies_filter[birdspecies_filter['Aircraft: Number of engines?'].isnull()]
filtered_dfnan

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
33,EGLIN AFB/NW FLORIDA REGIONAL ARPT,< 1000 ft,F-15E,1,1,Precautionary Landing,1/25/2000,Caused damage,NaN,MILITARY,...,True,"After takeoff, MP saw three large birds direct...",Large,No Cloud,Turkey vulture,Y,32827,400,0,No
196,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,2 to 10,10,None,4/6/2000,No damage,NaN,MILITARY,...,False,A bird struck the left inboard flap and one wa...,Medium,No Cloud,Unknown bird or bat,Y,0,1000,0,No
237,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,1,1,None,4/20/2000,No damage,NaN,MILITARY,...,False,Pigeon hit the #3 engine and ring cowl. No Da...,Medium,No Cloud,Unknown bird or bat,Y,0,0,0,No
348,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,1,1,None,5/16/2000,No damage,NaN,MILITARY,...,False,Bird type - Swallow. Bird struck just below t...,Medium,No Cloud,Unknown bird or bat,Y,0,25,0,No
354,BARKSDALE AIR FORCE BASE ARPT,> 1000 ft,B-52H,2 to 10,9,None,5/18/2000,No damage,NaN,MILITARY,...,True,Birdstrike on #1 main landing gear and above t...,Small,No Cloud,Cape May warbler,Y,0,1200,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24704,JOHN F KENNEDY INTL,< 1000 ft,CRJ-440,1,1,None,10/16/2011,No damage,NaN,PINNACLE,...,False,FLT 4176 REPORTS POSSIBLE BIRDSTRIKE WHILE LDG...,Small,No Cloud,Short-eared owl,Y,0,0,0,No
24726,FORT LAUDERDALE EXECUTIVE ARPT,< 1000 ft,PA-31-350,1,1,None,10/18/2011,No damage,NaN,BUSINESS,...,True,ID BY SMITHSONIAN. CARCASS RETRIEVED BY ARPT S...,Small,Overcast,American kestrel,N,0,20,0,No
24776,HONOLULU INTL ARPT,< 1000 ft,F/A-18,1,1,None,10/22/2011,No damage,NaN,HAWAIIAN AIR,...,False,BIRD HIT NOSE. RWY RETPD AT 08R AND 08L.,Small,No Cloud,Unknown bird - small,N,0,0,0,No
25086,KALAELOA ARPT JOHN RODGERS FIELD,< 1000 ft,DA-40,1,1,None,11/30/2011,No damage,NaN,BUSINESS,...,False,NO DMG TO A/C. CKD BY MX.,Small,No Cloud,Zebra dove,N,0,0,0,No
25126,ELLINGTON FIELD ARPT,< 1000 ft,T-38A,2 to 10,9,None,12/7/2011,No damage,NaN,GOVERNMENT,...,False,PILOT OBSERVED TWO GROUPS OF SMALL BIRDS (APPR...,Small,No Cloud,Unknown bird - small,N,0,15,0,No

In [192]:
filtered_engine_nan_percent = filtered_df_nan_engines[['Aircraft: Number of engines?', 'Remarks']]
filtered_engine_nan_percent

,Aircraft: Number of engines?,Remarks
3387,NaN,Large bird ingested down left engine. Severe ...
14909,NaN,"ID BY SMITHSONIAN, FAA 2606. 100% DNA MATCH. O..."

In [159]:
birdspecies_filter[birdspecies_filter['Aircraft: Make/Model'] == 'B-52H']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
196,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,2 to 10,10,None,4/6/2000,No damage,NaN,MILITARY,...,False,A bird struck the left inboard flap and one wa...,Medium,No Cloud,Unknown bird or bat,Y,0,1000,0,No
237,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,1,1,None,4/20/2000,No damage,NaN,MILITARY,...,False,Pigeon hit the #3 engine and ring cowl. No Da...,Medium,No Cloud,Unknown bird or bat,Y,0,0,0,No
348,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,1,1,None,5/16/2000,No damage,NaN,MILITARY,...,False,Bird type - Swallow. Bird struck just below t...,Medium,No Cloud,Unknown bird or bat,Y,0,25,0,No
354,BARKSDALE AIR FORCE BASE ARPT,> 1000 ft,B-52H,2 to 10,9,None,5/18/2000,No damage,NaN,MILITARY,...,True,Birdstrike on #1 main landing gear and above t...,Small,No Cloud,Cape May warbler,Y,0,1200,0,No
1277,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,2 to 10,5,None,11/13/2000,No damage,NaN,MILITARY,...,True,Bird impacted between the #7 and #8 engine wit...,Small,No Cloud,American pipit,Y,7879,500,0,No
1321,BARKSDALE AIR FORCE BASE ARPT,> 1000 ft,B-52H,1,1,None,12/1/2000,No damage,NaN,MILITARY,...,False,DURING THE AIRCREW POST FLIGHT WALK AROUND INS...,Medium,Some Cloud,Unknown bird or bat,Y,0,1800,0,No
1333,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,2 to 10,2,Precautionary Landing,12/12/2000,Caused damage,NaN,MILITARY,...,True,Post flight borescope of the #2 engine reveale...,Medium,No Cloud,Gadwall,Y,458207,500,0,No
1521,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,1,1,None,4/2/2001,No damage,NaN,MILITARY,...,False,A blood smear was found on post flight inspect...,Medium,No Cloud,Unknown bird or bat,Y,0,200,0,No
1539,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,1,1,Precautionary Landing,4/5/2001,No damage,NaN,MILITARY,...,False,NaN,Medium,No Cloud,Unknown bird or bat,Y,0,40,0,No
1569,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,1,1,Precautionary Landing,4/18/2001,No damage,NaN,MILITARY,...,True,NaN,Medium,No Cloud,American coot,Y,12029,800,0,No
1593,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,1,1,Precautionary Landing,4/27/2001,No damage,NaN,MILITARY,...,False,Aircraft struck a Chimney Swift bird during a ...,Medium,No Cloud,Unknown bird or bat,Y,0,1000,0,No
1594,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,1,1,Precautionary Landing,4/27/2001,No damage,NaN,MILITARY,...,False,NaN,Medium,No Cloud,Unknown bird or bat,Y,0,1000,0,No
1654,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,1,1,Precautionary Landing,5/15/2001,No damage,NaN,MILITARY,...,False,NaN,Medium,No Cloud,Unknown bird or bat,Y,0,1000,0,No
1680,BARKSDALE AIR FORCE BASE ARPT,> 1000 ft,B-52H,2 to 10,8,Precautionary Landing,5/23/2001,No damage,NaN,MILITARY,...,False,NaN,Medium,No Cloud,Unknown bird or bat,Y,0,1800,0,No
1763,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,1,1,None,6/17/2001,No damage,NaN,MILITARY,...,False,NaN,Medium,No Cloud,Unknown bird or bat,Y,0,100,0,No
2037,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,2 to 10,9,None,8/13/2001,No damage,NaN,MILITARY,...,True,NaN,Small,No Cloud,Mourning dove,Y,0,0,0,No
2054,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,1,1,Precautionary Landing,8/15/2001,No damage,NaN,MILITARY,...,False,NaN,Medium,No Cloud,Unknown bird or bat,Y,0,60,0,No
2423,BARKSDALE AIR FORCE BASE ARPT,> 1000 ft,B-52H,1,1,Precautionary Landing,10/24/2001,No damage,NaN,MILITARY,...,False,NaN,Medium,No Cloud,Unknown bird or bat,Y,0,3000,0,No
2650,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,2 to 10,3,None,2/14/2002,No damage,NaN,MILITARY,...,True,Structural maintenece evaluated both strikes a...,Small,No Cloud,American robin,Y,0,150,0,No
2935,BARKSDALE AIR FORCE BASE ARPT,> 1000 ft,B-52H,1,1,Precautionary Landing,5/7/2002,No damage,NaN,MILITARY,...,True,None.,Small,Some Cloud,American kestrel,Y,0,2000,0,No
3036,BARKSDALE AIR FORCE BASE ARPT,> 1000 ft,B-52H,2 to 10,9,None,5/23/2002,No damage,NaN,MILITARY,...,False,NaN,Medium,No Cloud,Unknown bird or bat,Y,0,2000,0,No
3206,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,2 to 10,7,None,7/1/2002,No damage,NaN,MILITARY,...,False,None.,Medium,No Cloud,Unknown bird or bat,Y,0,0,0,No
3283,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,1,1,Precautionary Landing,7/15/2002,No damage,NaN,MILITARY,...,True,During touch and go bird struck the top of the...,Small,Some Cloud,Barn swallow,Y,0,500,0,No
3299,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,1,1,None,7/18/2002,No damage,NaN,MILITARY,...,False,No damage found. No remains available for ide...,Medium,No Cloud,Unknown bird or bat,Y,0,0,0,No
3357,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,2 to 10,7,Precautionary Landing,7/25/2002,No damage,NaN,MILITARY,...,False,No damage found.,Medium,No Cloud,Unknown bird or bat,Y,0,0,0,No
3708,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,2 to 10,3,None,9/9/2002,No damage,NaN,MILITARY,...,False,No remains available for identification.,Medium,Some Cloud,Unknown bird or bat,Y,0,100,0,No
4120,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,1,1,None,11/12/2002,No damage,NaN,MILITARY,...,False,None.,Medium,No Cloud,Unknown bird or bat,Y,0,800,0,No
4126,BARKSDALE AIR FORCE BASE ARPT,> 1000 ft,B-52H,2 to 10,9,None,11/13/2002,No damage,NaN,MILITARY,...,False,None.,Medium,Overcast,Unknown bird or bat,Y,0,2000,0,No

In [239]:
# Filter the DataFrame for rows where 'Aircraft: Make/Model' is 'B-52H'
b52h_rows = birdspecies_filter[birdspecies_filter['Aircraft: Make/Model'] == 'B-52H']

# Fill NaN values in the 'Aircraft: Number of engines?' column for the filtered rows with the specified value (e.g., 8)
b52h_rows['Aircraft: Number of engines?'].fillna(8, inplace=True)

# Assign the filled values back to the original DataFrame using loc
birdspecies_filter.loc[birdspecies_filter['Aircraft: Make/Model'] == 'B-52H', 'Aircraft: Number of engines?'] = b52h_rows['Aircraft: Number of engines?']

# Display the updated DataFrame
print(birdspecies_filter)

                           Airport: Name Altitude bin Aircraft: Make/Model  \
0                       KANSAS CITY INTL    < 1000 ft                MD-80
1      CINCINNATI MUNI ARPT-LUNKEN FIELD    < 1000 ft          CITATION II
2                             MIAMI INTL    > 1000 ft              DA-2000
3            SOUTHWEST FLORIDA INTL ARPT    < 1000 ft           HAWKER 800
4                         NASHVILLE INTL    < 1000 ft            B-737-400
...                                  ...          ...                  ...
25198                       ORLANDO INTL    < 1000 ft                A-321
25199                  REDDING MUNICIPAL    > 1000 ft              EMB-120
25200    DETROIT METRO WAYNE COUNTY ARPT    < 1000 ft            B-757-200
25201       GEORGE BUSH INTERCONTINENTAL    < 1000 ft              EMB-145
25202       ABRAHAM LINCOLN CAPITAL ARPT    < 1000 ft            B-737-400

      Wildlife: Number struck  Wildlife: Number Struck Actual  \
0                   11 to 100                              54
1                           1                               1
2                           1                               1
3                           1                               1
4                           1                               1
...                       ...                             ...
25198                       1                               1
25199                       1                               1
25200                       1                               1
25201                 2 to 10                               6
25202                       1                               1

      Effect: Impact to flight  FlightDate Effect: Indicated Damage  \
0                         None    1/2/2000                No damage
1                         None    1/2/2000                No damage
2                         None    1/2/2000                No damage
3                         None    1/2/2000            Caused damage
4                         None    1/3/2000                No damage
...                        ...         ...                      ...
25198                     None  12/30/2011                No damage
25199                     None  12/30/2011                No damage
25200                     None  12/31/2011                No damage
25201                     None  12/31/2011                No damage
25202                     None  12/31/2011            Caused damage

       Aircraft: Number of engines? Aircraft: Airline/Operator  ...  \
0                               2.0       TRANS WORLD AIRLINES  ...
1                               2.0                   BUSINESS  ...
2                               2.0                   BUSINESS  ...
3                               2.0                   BUSINESS  ...
4                               2.0                US AIRWAYS*  ...
...                             ...                        ...  ...
25198                           2.0                 US AIRWAYS  ...
25199                           2.0           SKYWEST AIRLINES  ...
25200                           2.0            DELTA AIR LINES  ...
25201                           2.0         ATLANTIC SOUTHEAST  ...
25202                           2.0               XTRA AIRWAYS  ...

      Remains of wildlife sent to Smithsonian  \
0                                       False
1                                       False
2                                       False
3                                       False
4                                       False
...                                       ...
25198                                   False
25199                                   False
25200                                   False
25201                                   False
25202                                   False

                                                 Remarks Wildlife: Size  \
0                                                    NaN          Large
1                                                    NaN          Small
2                                                    NaN         Medium
3      SUSPECT GULL. HEARD THUMP ON APCH BUT NO ABNRM...         Medium
4                                                    NaN          Small
...                                                  ...            ...
25198                                                NaN          Small
25199                                DUCK? NO DMG REPTD.          Large
25200  PILOTS REPORT STRIKING UNKNOWN BIRD ON RWY 21L...         Medium
25201                                                NaN          Small
25202  HIT CENTER OF RADOME, CAVING IN ABOUT 12". RAD...         Medium

       Conditions: Sky      Wildlife: Species  \
0             No Cloud           Canada goose
1             Overcast   Unknown bird - small
2             No Cloud  Unknown bird - medium
3             No Cloud  Unknown bird - medium
4           Some Cloud   Unknown bird - small
...                ...                    ...
25198       Some Cloud           Tree swallow
25199         Overcast   Unknown bird - large
25200       Some Cloud  Unknown bird - medium
25201         Overcast   Unknown bird - small
25202         No Cloud        Red-tailed hawk

      Pilot warned of birds or wildlife? Cost: Total $ Feet above ground  \
0                                      N             0               350
1                                      N             0                 0
2                                      Y             0              2000
3                                      Y        120273               200
4                                      Y             0               800
...                                  ...           ...               ...
25198                                  Y             0                 0
25199                                  N             0              1500
25200                                  Y             0                 0
25201                                  Y             0                 0
25202                                  N             0                 0

      Number of people injured Is Aircraft Large?
0                            0                 No
1                            0                 No
2                            0                 No
3                            0                 No
4                            0                Yes
...                        ...                ...
25198                        0                 No
25199                        0                 No
25200                        0                Yes
25201                        0                 No
25202                        0                Yes

[25203 rows x 24 columns]

C:\Users\HP\AppData\Local\Temp\ipykernel_17440\4082459865.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  b52h_rows['Aircraft: Number of engines?'].fillna(8, inplace=True)

In [240]:
birdspecies_filter.isnull().sum()

Airport: Name                                 0
Altitude bin                                  0
Aircraft: Make/Model                          0
Wildlife: Number struck                       0
Wildlife: Number Struck Actual                0
Effect: Impact to flight                      0
FlightDate                                    0
Effect: Indicated Damage                      0
Aircraft: Number of engines?                197
Aircraft: Airline/Operator                    0
Origin State                                449
When: Phase of flight                         0
Conditions: Precipitation                     0
Remains of wildlife collected?                0
Remains of wildlife sent to Smithsonian       0
Remarks                                    4752
Wildlife: Size                                0
Conditions: Sky                               0
Wildlife: Species                             0
Pilot warned of birds or wildlife?            0
Cost: Total $                                 0
Feet above ground                             0
Number of people injured                      0
Is Aircraft Large?                            0
dtype: int64

In [243]:
birdspecies_filter[birdspecies_filter['Aircraft: Make/Model'] == 'T-38A']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
556,SHEPPARD AIR FORCE BASE,< 1000 ft,T-38A,1,1,None,7/10/2000,No damage,2.0,MILITARY,...,False,impact on nose,Medium,No Cloud,Unknown bird or bat,Y,21,2,0,No
1388,SHEPPARD AIR FORCE BASE,> 1000 ft,T-38A,1,1,Precautionary Landing,1/20/2001,No damage,2.0,MILITARY,...,True,NaN,Small,No Cloud,Horned lark,Y,21,2000,0,No
1403,SHEPPARD AIR FORCE BASE,> 1000 ft,T-38A,1,1,Precautionary Landing,2/1/2001,Caused damage,2.0,MILITARY,...,True,"LT LICCARDO , J FLIGHT, 7177",Medium,No Cloud,Pied-billed grebe,Y,39983,2800,0,No
1460,SHEPPARD AIR FORCE BASE,> 1000 ft,T-38A,2 to 10,3,Precautionary Landing,3/5/2001,No damage,2.0,MILITARY,...,False,NaN,Medium,No Cloud,Unknown bird or bat,Y,1,1800,0,No
1461,SHEPPARD AIR FORCE BASE,> 1000 ft,T-38A,1,1,Precautionary Landing,3/5/2001,No damage,2.0,MILITARY,...,True,NaN,Small,No Cloud,American robin,Y,1,1800,0,No
1562,SHEPPARD AIR FORCE BASE,< 1000 ft,T-38A,1,1,Precautionary Landing,4/16/2001,No damage,2.0,MILITARY,...,True,NaN,Small,Some Cloud,Upland sandpiper,Y,0,300,0,No
1757,SHEPPARD AIR FORCE BASE,< 1000 ft,T-38A,1,1,None,6/14/2001,No damage,2.0,MILITARY,...,False,NaN,Medium,No Cloud,Unknown bird or bat,Y,0,0,0,No
2009,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,T-38A,1,1,Precautionary Landing,8/9/2001,No damage,2.0,MILITARY,...,True,NaN,Small,No Cloud,American robin,Y,0,450,0,No
2335,SHEPPARD AIR FORCE BASE,< 1000 ft,T-38A,1,1,None,10/4/2001,No damage,2.0,MILITARY,...,False,Bird hit left wing prior,Medium,No Cloud,Unknown bird or bat,Y,0,400,0,No
2467,SHEPPARD AIR FORCE BASE,< 1000 ft,T-38A,2 to 10,9,Precautionary Landing,11/6/2001,No damage,2.0,MILITARY,...,True,"BIRD REMAINS WILL BE SENT AS SOON AS POSSIBLE,...",Small,No Cloud,Common grackle,Y,0,400,0,No
2468,SHEPPARD AIR FORCE BASE,< 1000 ft,T-38A,1,1,None,11/6/2001,No damage,2.0,MILITARY,...,True,BIRD REMAINS WILL STAY AT SHEPPARD AFB UNTIL E...,Small,No Cloud,Mourning dove,Y,0,0,0,No
2725,SHEPPARD AIR FORCE BASE,< 1000 ft,T-38A,1,1,Precautionary Landing,3/26/2002,No damage,2.0,MILITARY,...,True,"On two-mile final during a no-flap approach, t...",Small,No Cloud,Mourning dove,Y,19016,800,0,No
2967,SHEPPARD AIR FORCE BASE,< 1000 ft,T-38A,1,1,Aborted Take-off,5/13/2002,No damage,2.0,MILITARY,...,True,NaN,Small,No Cloud,Eastern meadowlark,Y,0,0,0,No
3153,SHEPPARD AIR FORCE BASE,< 1000 ft,T-38A,1,1,None,6/19/2002,No damage,2.0,MILITARY,...,False,NaN,Medium,No Cloud,Unknown bird or bat,Y,0,0,0,No
3387,SHEPPARD AIR FORCE BASE,< 1000 ft,T-38A,1,1,Precautionary Landing,7/28/2002,Caused damage,2.0,MILITARY,...,False,Large bird ingested down left engine. Severe ...,Medium,Some Cloud,Unknown bird or bat,Y,103955,500,0,No
3879,SHEPPARD AIR FORCE BASE,< 1000 ft,T-38A,1,1,Precautionary Landing,10/3/2002,No damage,2.0,MILITARY,...,False,NaN,Medium,No Cloud,Unknown bird or bat,Y,0,10,0,No
3931,EDWARDS AIR FORCE BASE,< 1000 ft,T-38A,1,1,Precautionary Landing,10/10/2002,No damage,2.0,MILITARY,...,False,NaN,Medium,No Cloud,Unknown bird or bat,Y,0,400,0,No
3932,SHEPPARD AIR FORCE BASE,< 1000 ft,T-38A,1,1,Aborted Take-off,10/10/2002,Caused damage,2.0,MILITARY,...,False,The aircraft sruck and killed a Coyote on runw...,Medium,No Cloud,Unknown bird or bat,Y,127,0,0,No
6370,ELLINGTON FIELD ARPT,< 1000 ft,T-38A,1,1,Aborted Take-off,6/27/2004,Caused damage,2.0,GOVERNMENT,...,True,ID BY SMITHSONIAN FAA 784. ENG COMPLETELY DEST...,Small,Some Cloud,Barn owl,N,0,0,0,No
7960,ELLINGTON FIELD ARPT,< 1000 ft,T-38A,1,1,Other,5/31/2005,No damage,2.0,GOVERNMENT,...,False,PERFORMING TOUCH & GO'S. ELECTED TO PERFORM A ...,Small,Overcast,Barn owl,N,0,3,0,No
11245,ELLINGTON FIELD ARPT,< 1000 ft,T-38A,1,1,None,11/6/2006,No damage,2.0,GOVERNMENT,...,False,"# STRUCK NOT REPTD, ASSUME 1. AC REPTD AS GULF...",Small,Some Cloud,Unknown bird - small,Y,0,0,0,No
14909,ELLINGTON FIELD ARPT,< 1000 ft,T-38A,1,1,Other,8/7/2008,Caused damage,2.0,GOVERNMENT,...,True,"ID BY SMITHSONIAN, FAA 2606. 100% DNA MATCH. O...",Small,Some Cloud,Killdeer,Y,25391,0,0,No
16188,ELLINGTON FIELD ARPT,< 1000 ft,T-38A,1,1,None,3/9/2009,No damage,2.0,GOVERNMENT,...,False,REMAINS WERE REPORTED BY A DEPARTING A/C. N919...,Small,Some Cloud,Eastern meadowlark,N,0,38,0,No
16276,ELLINGTON FIELD ARPT,< 1000 ft,T-38A,1,1,None,3/25/2009,No damage,2.0,GOVERNMENT,...,False,NO DMG. NO BIRD WAS RECOVERED.,Small,Some Cloud,Unknown bird - small,N,0,62,0,No
17312,ELLINGTON FIELD ARPT,< 1000 ft,T-38A,1,1,None,7/17/2009,No damage,2.0,GOVERNMENT,...,False,PILOT REPTD BIRDSTRIKE ON L/R.,Small,Overcast,Barn swallow,Y,0,32,0,No
19405,ELLINGTON FIELD ARPT,> 1000 ft,T-38A,1,1,None,3/4/2010,No damage,2.0,GOVERNMENT,...,False,A/C DMG BEING INVESTIGATED. NO INJURIES. INITI...,Medium,No Cloud,Unknown bird - medium,N,0,2200,0,No
24608,ELLINGTON FIELD ARPT,< 1000 ft,T-38A,1,1,None,10/7/2011,No damage,2.0,GOVERNMENT,...,True,ID BY SMITHSONIAN. FAA 6666. DNA.,Small,No Cloud,Cliff swallow,N,0,0,0,No
25126,ELLINGTON FIELD ARPT,< 1000 ft,T-38A,2 to 10,9,None,12/7/2011,No damage,2.0,GOVERNMENT,...,False,PILOT OBSERVED TWO GROUPS OF SMALL BIRDS (APPR...,Small,No Cloud,Unknown bird - small,N,0,15,0,No

In [206]:
filtered_df_nan_engines

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
10167,LONG ISLAND MAC ARTHUR,< 1000 ft,AMD ALARUS CH2000,1,1,None,7/13/2006,No damage,NaN,BUSINESS,...,False,NO DMG TO A/C. (NO ICAO CODE FOR THIS SINGLE E...,Small,Overcast,Unknown bird - small,N,0,0,0,No
11414,LINCOLN MUNICIPAL,< 1000 ft,CRJ-440,1,1,Engine Shut Down,12/16/2006,Caused damage,NaN,PINNACLE,...,True,"ID BY SMITHSONIAN, FAA 1709. PHOTOS. DMG TO R...",Large,Overcast,Canada goose,Y,7530,800,0,No
13036,LORAIN COUNTY REGIONAL ARPT,< 1000 ft,MISC - OTHER,2 to 10,10,None,9/9/2007,No damage,NaN,PRIVATELY OWNED,...,False,A/C -FLIGHT DESIGN CTSW. (SINGLE ENG PROP BUIL...,Small,Some Cloud,Mourning dove,Y,0,25,0,No
15633,GROTON-NEW LONDON AR,< 1000 ft,ECLIPSE 500,1,1,None,10/26/2008,No damage,NaN,PRIVATELY OWNED,...,False,"ON APCH, CLIPPED THE WING OF A BIRD. NO DMG. W...",Medium,Some Cloud,Unknown bird - medium,Y,0,500,0,No
16197,JOE FOSS FIELD ARPT,< 1000 ft,CITATION MUSTANG 510,2 to 10,4,Precautionary Landing,3/10/2009,Caused damage,NaN,BUSINESS,...,False,BIRD REPTD AS BLUE GOOSE. DMG TO LWR L ENG COW...,Large,Overcast,Snow goose,N,31624,500,0,No
17446,NEVADA COUNTY AIR PARK,< 1000 ft,GRUMMAN S-2 TRACKER,1,1,None,7/25/2009,Caused damage,NaN,BUSINESS,...,False,PILOT SAW 2 KILLDEER ON BASE TO FINAL AND TRIE...,Small,No Cloud,Killdeer,N,263533,320,0,No
18228,WESTCHESTER COUNTY ARPT,< 1000 ft,BD-700,1,1,None,9/16/2009,No damage,NaN,BUSINESS,...,False,BIRDSTRIKE LANDING OVER NUMBERS ON RWY 16. CAP...,Small,Overcast,Unknown bird - small,Y,0,0,0,No
23568,KLAMATH FALLS INTL,< 1000 ft,B-787-800,2 to 10,4,None,7/22/2011,No damage,NaN,BOEING COMMERCIAL AIRPLANE GRP,...,True,ID BY SMITHSONIAN. A/C HIT BIRDS RWY 32 UNDER ...,Medium,No Cloud,California gull,N,0,100,0,No
24580,CAPE COD COAST GUARD AIR STATION,< 1000 ft,HU-25,2 to 10,6,Precautionary Landing,10/5/2011,No damage,NaN,GOVERNMENT,...,True,"ID BY SMITHSONIAN, MULTIPLE SPECIES. BAGS 1 A...",Small,Some Cloud,Black-bellied plover,N,0,0,0,No

In [241]:
t38a_rows = birdspecies_filter[birdspecies_filter['Aircraft: Make/Model'] == 'T-38A']

# Fill NaN values in the 'Aircraft: Number of engines?' column for the filtered rows with the specified value (e.g., 8)
t38a_rows['Aircraft: Number of engines?'].fillna(2, inplace=True)

# Assign the filled values back to the original DataFrame using loc
birdspecies_filter.loc[birdspecies_filter['Aircraft: Make/Model'] == 'T-38A', 'Aircraft: Number of engines?'] = t38a_rows['Aircraft: Number of engines?']

# Display the updated DataFrame
print(birdspecies_filter)

                           Airport: Name Altitude bin Aircraft: Make/Model  \
0                       KANSAS CITY INTL    < 1000 ft                MD-80
1      CINCINNATI MUNI ARPT-LUNKEN FIELD    < 1000 ft          CITATION II
2                             MIAMI INTL    > 1000 ft              DA-2000
3            SOUTHWEST FLORIDA INTL ARPT    < 1000 ft           HAWKER 800
4                         NASHVILLE INTL    < 1000 ft            B-737-400
...                                  ...          ...                  ...
25198                       ORLANDO INTL    < 1000 ft                A-321
25199                  REDDING MUNICIPAL    > 1000 ft              EMB-120
25200    DETROIT METRO WAYNE COUNTY ARPT    < 1000 ft            B-757-200
25201       GEORGE BUSH INTERCONTINENTAL    < 1000 ft              EMB-145
25202       ABRAHAM LINCOLN CAPITAL ARPT    < 1000 ft            B-737-400

      Wildlife: Number struck  Wildlife: Number Struck Actual  \
0                   11 to 100                              54
1                           1                               1
2                           1                               1
3                           1                               1
4                           1                               1
...                       ...                             ...
25198                       1                               1
25199                       1                               1
25200                       1                               1
25201                 2 to 10                               6
25202                       1                               1

      Effect: Impact to flight  FlightDate Effect: Indicated Damage  \
0                         None    1/2/2000                No damage
1                         None    1/2/2000                No damage
2                         None    1/2/2000                No damage
3                         None    1/2/2000            Caused damage
4                         None    1/3/2000                No damage
...                        ...         ...                      ...
25198                     None  12/30/2011                No damage
25199                     None  12/30/2011                No damage
25200                     None  12/31/2011                No damage
25201                     None  12/31/2011                No damage
25202                     None  12/31/2011            Caused damage

       Aircraft: Number of engines? Aircraft: Airline/Operator  ...  \
0                               2.0       TRANS WORLD AIRLINES  ...
1                               2.0                   BUSINESS  ...
2                               2.0                   BUSINESS  ...
3                               2.0                   BUSINESS  ...
4                               2.0                US AIRWAYS*  ...
...                             ...                        ...  ...
25198                           2.0                 US AIRWAYS  ...
25199                           2.0           SKYWEST AIRLINES  ...
25200                           2.0            DELTA AIR LINES  ...
25201                           2.0         ATLANTIC SOUTHEAST  ...
25202                           2.0               XTRA AIRWAYS  ...

      Remains of wildlife sent to Smithsonian  \
0                                       False
1                                       False
2                                       False
3                                       False
4                                       False
...                                       ...
25198                                   False
25199                                   False
25200                                   False
25201                                   False
25202                                   False

                                                 Remarks Wildlife: Size  \
0                                                    NaN          Large
1                                                    NaN          Small
2                                                    NaN         Medium
3      SUSPECT GULL. HEARD THUMP ON APCH BUT NO ABNRM...         Medium
4                                                    NaN          Small
...                                                  ...            ...
25198                                                NaN          Small
25199                                DUCK? NO DMG REPTD.          Large
25200  PILOTS REPORT STRIKING UNKNOWN BIRD ON RWY 21L...         Medium
25201                                                NaN          Small
25202  HIT CENTER OF RADOME, CAVING IN ABOUT 12". RAD...         Medium

       Conditions: Sky      Wildlife: Species  \
0             No Cloud           Canada goose
1             Overcast   Unknown bird - small
2             No Cloud  Unknown bird - medium
3             No Cloud  Unknown bird - medium
4           Some Cloud   Unknown bird - small
...                ...                    ...
25198       Some Cloud           Tree swallow
25199         Overcast   Unknown bird - large
25200       Some Cloud  Unknown bird - medium
25201         Overcast   Unknown bird - small
25202         No Cloud        Red-tailed hawk

      Pilot warned of birds or wildlife? Cost: Total $ Feet above ground  \
0                                      N             0               350
1                                      N             0                 0
2                                      Y             0              2000
3                                      Y        120273               200
4                                      Y             0               800
...                                  ...           ...               ...
25198                                  Y             0                 0
25199                                  N             0              1500
25200                                  Y             0                 0
25201                                  Y             0                 0
25202                                  N             0                 0

      Number of people injured Is Aircraft Large?
0                            0                 No
1                            0                 No
2                            0                 No
3                            0                 No
4                            0                Yes
...                        ...                ...
25198                        0                 No
25199                        0                 No
25200                        0                Yes
25201                        0                 No
25202                        0                Yes

[25203 rows x 24 columns]

C:\Users\HP\AppData\Local\Temp\ipykernel_17440\4223778457.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t38a_rows['Aircraft: Number of engines?'].fillna(2, inplace=True)

In [244]:
birdspecies_filter.isnull().sum()

Airport: Name                                 0
Altitude bin                                  0
Aircraft: Make/Model                          0
Wildlife: Number struck                       0
Wildlife: Number Struck Actual                0
Effect: Impact to flight                      0
FlightDate                                    0
Effect: Indicated Damage                      0
Aircraft: Number of engines?                169
Aircraft: Airline/Operator                    0
Origin State                                449
When: Phase of flight                         0
Conditions: Precipitation                     0
Remains of wildlife collected?                0
Remains of wildlife sent to Smithsonian       0
Remarks                                    4752
Wildlife: Size                                0
Conditions: Sky                               0
Wildlife: Species                             0
Pilot warned of birds or wildlife?            0
Cost: Total $                                 0
Feet above ground                             0
Number of people injured                      0
Is Aircraft Large?                            0
dtype: int64

In [208]:
birdspecies_filter[birdspecies_filter['Aircraft: Make/Model'] == 'CRJ-440']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
9804,DETROIT METRO WAYNE COUNTY ARPT,< 1000 ft,CRJ-440,1,1,None,5/15/2006,No damage,NaN,PINNACLE,...,False,STRIKE LOCATION 22R @ A-3 INTXN,Small,Overcast,Red-winged blackbird,Y,0,0,0,No
9983,DETROIT METRO WAYNE COUNTY ARPT,< 1000 ft,CRJ-440,1,1,None,6/18/2006,No damage,NaN,PINNACLE,...,True,"ID BY SMITHSONIAN. ,A/C IS BOMBARDIER CRJ 440...",Small,Some Cloud,Savannah sparrow,Y,0,50,0,No
10153,DETROIT METRO WAYNE COUNTY ARPT,< 1000 ft,CRJ-440,1,1,None,7/12/2006,No damage,NaN,PINNACLE,...,False,REMAINS FOUND NEAR A-7 INTXN DURING POST STRIK...,Small,Overcast,European starling,Y,0,0,0,No
10204,MEMPHIS INTL,< 1000 ft,CRJ-440,2 to 10,10,None,7/18/2006,No damage,NaN,PINNACLE,...,False,NO VIZ DMG,Small,Some Cloud,Rock pigeon,N,0,0,0,No
10205,DETROIT METRO WAYNE COUNTY ARPT,< 1000 ft,CRJ-440,2 to 10,5,None,7/18/2006,No damage,NaN,PINNACLE,...,False,FLT CREW REPTD SEEING 3 DOVES ON RWY PRIOR TO ...,Small,Some Cloud,Mourning dove,Y,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20857,OUTAGAMIE COUNTY REGIONAL,< 1000 ft,CRJ-440,1,1,None,8/11/2010,No damage,NaN,PINNACLE,...,False,WALKED AROUND A/C. NO MARKS FOUND.,Small,Some Cloud,Killdeer,N,0,0,0,No
21233,DETROIT METRO WAYNE COUNTY ARPT,< 1000 ft,CRJ-440,1,1,None,9/3/2010,No damage,NaN,PINNACLE,...,False,ONE RED-TAILED HAWK REMVD FROM RWY 22L AT 3000...,Medium,Some Cloud,Red-tailed hawk,Y,0,0,0,No
23020,DETROIT METRO WAYNE COUNTY ARPT,< 1000 ft,CRJ-440,1,1,None,5/22/2011,No damage,NaN,PINNACLE,...,False,GRND MX REMVD STRIKE DEBRIS AND DISPOSED TO TO...,Small,Some Cloud,Unknown bird - small,Y,0,0,0,No
23770,QUAD CITY ARPT,< 1000 ft,CRJ-440,1,1,None,8/6/2011,No damage,NaN,MESABA AIRLINES,...,False,ATIS WARNING. ONE STARLING STRUCK. NO REPTD DMG.,Small,Overcast,European starling,Y,0,0,0,No
24704,JOHN F KENNEDY INTL,< 1000 ft,CRJ-440,1,1,None,10/16/2011,No damage,NaN,PINNACLE,...,False,FLT 4176 REPORTS POSSIBLE BIRDSTRIKE WHILE LDG...,Small,No Cloud,Short-eared owl,Y,0,0,0,No

In [209]:
filtered_df_nan_engines

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
10167,LONG ISLAND MAC ARTHUR,< 1000 ft,AMD ALARUS CH2000,1,1,None,7/13/2006,No damage,NaN,BUSINESS,...,False,NO DMG TO A/C. (NO ICAO CODE FOR THIS SINGLE E...,Small,Overcast,Unknown bird - small,N,0,0,0,No
11414,LINCOLN MUNICIPAL,< 1000 ft,CRJ-440,1,1,Engine Shut Down,12/16/2006,Caused damage,NaN,PINNACLE,...,True,"ID BY SMITHSONIAN, FAA 1709. PHOTOS. DMG TO R...",Large,Overcast,Canada goose,Y,7530,800,0,No
13036,LORAIN COUNTY REGIONAL ARPT,< 1000 ft,MISC - OTHER,2 to 10,10,None,9/9/2007,No damage,NaN,PRIVATELY OWNED,...,False,A/C -FLIGHT DESIGN CTSW. (SINGLE ENG PROP BUIL...,Small,Some Cloud,Mourning dove,Y,0,25,0,No
15633,GROTON-NEW LONDON AR,< 1000 ft,ECLIPSE 500,1,1,None,10/26/2008,No damage,NaN,PRIVATELY OWNED,...,False,"ON APCH, CLIPPED THE WING OF A BIRD. NO DMG. W...",Medium,Some Cloud,Unknown bird - medium,Y,0,500,0,No
16197,JOE FOSS FIELD ARPT,< 1000 ft,CITATION MUSTANG 510,2 to 10,4,Precautionary Landing,3/10/2009,Caused damage,NaN,BUSINESS,...,False,BIRD REPTD AS BLUE GOOSE. DMG TO LWR L ENG COW...,Large,Overcast,Snow goose,N,31624,500,0,No
17446,NEVADA COUNTY AIR PARK,< 1000 ft,GRUMMAN S-2 TRACKER,1,1,None,7/25/2009,Caused damage,NaN,BUSINESS,...,False,PILOT SAW 2 KILLDEER ON BASE TO FINAL AND TRIE...,Small,No Cloud,Killdeer,N,263533,320,0,No
18228,WESTCHESTER COUNTY ARPT,< 1000 ft,BD-700,1,1,None,9/16/2009,No damage,NaN,BUSINESS,...,False,BIRDSTRIKE LANDING OVER NUMBERS ON RWY 16. CAP...,Small,Overcast,Unknown bird - small,Y,0,0,0,No
23568,KLAMATH FALLS INTL,< 1000 ft,B-787-800,2 to 10,4,None,7/22/2011,No damage,NaN,BOEING COMMERCIAL AIRPLANE GRP,...,True,ID BY SMITHSONIAN. A/C HIT BIRDS RWY 32 UNDER ...,Medium,No Cloud,California gull,N,0,100,0,No
24580,CAPE COD COAST GUARD AIR STATION,< 1000 ft,HU-25,2 to 10,6,Precautionary Landing,10/5/2011,No damage,NaN,GOVERNMENT,...,True,"ID BY SMITHSONIAN, MULTIPLE SPECIES. BAGS 1 A...",Small,Some Cloud,Black-bellied plover,N,0,0,0,No

In [210]:
birdspecies_filter['Effect: Indicated Damage'].unique()

array(['No damage', 'Caused damage'], dtype=object)

In [261]:
filtered_df1 = birdspecies_filter[birdspecies_filter['Aircraft: Number of engines?'] == 1]
filtered_df2 = birdspecies_filter[birdspecies_filter['Aircraft: Number of engines?'] == 2]
filtered_df3 = birdspecies_filter[birdspecies_filter['Aircraft: Number of engines?'] == 3]
filtered_df4 = birdspecies_filter[birdspecies_filter['Aircraft: Number of engines?'] == 4]
filtered_dfnan = birdspecies_filter[birdspecies_filter['Aircraft: Number of engines?'].isnull()]



filtered_df_effect1 = filtered_df1[filtered_df1['Effect: Indicated Damage'] == 'Caused damage'] 
filtered_df_effect2 = filtered_df2[filtered_df2['Effect: Indicated Damage'] == 'Caused damage']
filtered_df_effect3 = filtered_df3[filtered_df3['Effect: Indicated Damage'] == 'Caused damage']
filtered_df_effect4 = filtered_df4[filtered_df4['Effect: Indicated Damage'] == 'Caused damage']
filtered_df_effectnan = filtered_dfnan[filtered_dfnan['Effect: Indicated Damage'] == 'Caused damage']

filtered_df_engine1 = filtered_df_effect1[filtered_df_effect1['Remarks'].str.contains('eng', case=False, na=False)]
filtered_df_engine2 = filtered_df_effect2[filtered_df_effect2['Remarks'].str.contains('eng', case=False, na=False)]
filtered_df_engine3 = filtered_df_effect3[filtered_df_effect3['Remarks'].str.contains('eng', case=False, na=False)]
filtered_df_engine4 = filtered_df_effect4[filtered_df_effect4['Remarks'].str.contains('eng', case=False, na=False)]
filtered_df_nan_engines = filtered_df_effectnan[filtered_df_effectnan['Remarks'].str.contains('eng', case=False, na=False)]
# Step 2: Optionally, select specific columns of interest
# result = filtered_df[['Column1', 'Column2']]  # replace 'Column1' and 'Column2' with actual column names

# Display the filtered result
filtered_engine1_percent = filtered_df_engine1[['Aircraft: Number of engines?', 'Remarks']].shape[0]
filtered_engine2_percent = filtered_df_engine2[['Aircraft: Number of engines?', 'Remarks']].shape[0]
filtered_engine3_percent = filtered_df_engine3[['Aircraft: Number of engines?', 'Remarks']].shape[0]
filtered_engine4_percent = filtered_df_engine4[['Aircraft: Number of engines?', 'Remarks']].shape[0]
filtered_engine_nan_percent = filtered_df_nan_engines[['Aircraft: Number of engines?', 'Remarks']].shape[0]

total_percent_remarks = birdspecies_filter['Remarks'].shape[0]

print(f"Percentage of wildlife struck with aircraft having only one engine:{(filtered_engine1_percent/total_percent_remarks)*100:.2f}%")
print(f"Percentage of wildlife struck with aircraft having only two engines:{(filtered_engine2_percent/total_percent_remarks)*100:.2f}%") 
print(f"Percentage of wildlife struck with aircraft having only three engines:{(filtered_engine3_percent/total_percent_remarks)*100:.2f}%")
print(f"Percentage of wildlife struck with aircraft having only four engines:{(filtered_engine4_percent/total_percent_remarks)*100:.2f}%")        
print(f"Percentage of wildlife struck with aircraft having only nan values:{(filtered_engine_nan_percent/total_percent_remarks)*100:.2f}%")

Percentage of wildlife struck with aircraft having only one engine:0.07%
Percentage of wildlife struck with aircraft having only two engines:2.51%
Percentage of wildlife struck with aircraft having only three engines:0.07%
Percentage of wildlife struck with aircraft having only four engines:0.08%
Percentage of wildlife struck with aircraft having only nan values:0.00%

In [262]:
crj440_rows = birdspecies_filter[birdspecies_filter['Aircraft: Make/Model'] == 'CRJ-440']

# Fill NaN values in the 'Aircraft: Number of engines?' column for the filtered rows with the specified value (e.g., 8)
crj440_rows['Aircraft: Number of engines?'].fillna(2, inplace=True)

# Assign the filled values back to the original DataFrame using loc
birdspecies_filter.loc[birdspecies_filter['Aircraft: Make/Model'] == 'CRJ-440', 'Aircraft: Number of engines?'] = crj440_rows['Aircraft: Number of engines?']

# Display the updated DataFrame
print(birdspecies_filter)

                           Airport: Name Altitude bin Aircraft: Make/Model  \
0                       KANSAS CITY INTL    < 1000 ft                MD-80
1      CINCINNATI MUNI ARPT-LUNKEN FIELD    < 1000 ft          CITATION II
2                             MIAMI INTL    > 1000 ft              DA-2000
3            SOUTHWEST FLORIDA INTL ARPT    < 1000 ft           HAWKER 800
4                         NASHVILLE INTL    < 1000 ft            B-737-400
...                                  ...          ...                  ...
25198                       ORLANDO INTL    < 1000 ft                A-321
25199                  REDDING MUNICIPAL    > 1000 ft              EMB-120
25200    DETROIT METRO WAYNE COUNTY ARPT    < 1000 ft            B-757-200
25201       GEORGE BUSH INTERCONTINENTAL    < 1000 ft              EMB-145
25202       ABRAHAM LINCOLN CAPITAL ARPT    < 1000 ft            B-737-400

      Wildlife: Number struck  Wildlife: Number Struck Actual  \
0                   11 to 100                              54
1                           1                               1
2                           1                               1
3                           1                               1
4                           1                               1
...                       ...                             ...
25198                       1                               1
25199                       1                               1
25200                       1                               1
25201                 2 to 10                               6
25202                       1                               1

      Effect: Impact to flight  FlightDate Effect: Indicated Damage  \
0                         None    1/2/2000                No damage
1                         None    1/2/2000                No damage
2                         None    1/2/2000                No damage
3                         None    1/2/2000            Caused damage
4                         None    1/3/2000                No damage
...                        ...         ...                      ...
25198                     None  12/30/2011                No damage
25199                     None  12/30/2011                No damage
25200                     None  12/31/2011                No damage
25201                     None  12/31/2011                No damage
25202                     None  12/31/2011            Caused damage

       Aircraft: Number of engines? Aircraft: Airline/Operator  ...  \
0                               2.0       TRANS WORLD AIRLINES  ...
1                               2.0                   BUSINESS  ...
2                               2.0                   BUSINESS  ...
3                               2.0                   BUSINESS  ...
4                               2.0                US AIRWAYS*  ...
...                             ...                        ...  ...
25198                           2.0                 US AIRWAYS  ...
25199                           2.0           SKYWEST AIRLINES  ...
25200                           2.0            DELTA AIR LINES  ...
25201                           2.0         ATLANTIC SOUTHEAST  ...
25202                           2.0               XTRA AIRWAYS  ...

      Remains of wildlife sent to Smithsonian  \
0                                       False
1                                       False
2                                       False
3                                       False
4                                       False
...                                       ...
25198                                   False
25199                                   False
25200                                   False
25201                                   False
25202                                   False

                                                 Remarks Wildlife: Size  \
0                                                    NaN          Large
1                                                    NaN          Small
2                                                    NaN         Medium
3      SUSPECT GULL. HEARD THUMP ON APCH BUT NO ABNRM...         Medium
4                                                    NaN          Small
...                                                  ...            ...
25198                                                NaN          Small
25199                                DUCK? NO DMG REPTD.          Large
25200  PILOTS REPORT STRIKING UNKNOWN BIRD ON RWY 21L...         Medium
25201                                                NaN          Small
25202  HIT CENTER OF RADOME, CAVING IN ABOUT 12". RAD...         Medium

       Conditions: Sky      Wildlife: Species  \
0             No Cloud           Canada goose
1             Overcast   Unknown bird - small
2             No Cloud  Unknown bird - medium
3             No Cloud  Unknown bird - medium
4           Some Cloud   Unknown bird - small
...                ...                    ...
25198       Some Cloud           Tree swallow
25199         Overcast   Unknown bird - large
25200       Some Cloud  Unknown bird - medium
25201         Overcast   Unknown bird - small
25202         No Cloud        Red-tailed hawk

      Pilot warned of birds or wildlife? Cost: Total $ Feet above ground  \
0                                      N             0               350
1                                      N             0                 0
2                                      Y             0              2000
3                                      Y        120273               200
4                                      Y             0               800
...                                  ...           ...               ...
25198                                  Y             0                 0
25199                                  N             0              1500
25200                                  Y             0                 0
25201                                  Y             0                 0
25202                                  N             0                 0

      Number of people injured Is Aircraft Large?
0                            0                 No
1                            0                 No
2                            0                 No
3                            0                 No
4                            0                Yes
...                        ...                ...
25198                        0                 No
25199                        0                 No
25200                        0                Yes
25201                        0                 No
25202                        0                Yes

[25203 rows x 24 columns]

C:\Users\HP\AppData\Local\Temp\ipykernel_17440\2613351978.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crj440_rows['Aircraft: Number of engines?'].fillna(2, inplace=True)

In [254]:
birdspecies_filter.isnull().sum()

Airport: Name                                 0
Altitude bin                                  0
Aircraft: Make/Model                          0
Wildlife: Number struck                       0
Wildlife: Number Struck Actual                0
Effect: Impact to flight                      0
FlightDate                                    0
Effect: Indicated Damage                      0
Aircraft: Number of engines?                 95
Aircraft: Airline/Operator                    0
Origin State                                449
When: Phase of flight                         0
Conditions: Precipitation                     0
Remains of wildlife collected?                0
Remains of wildlife sent to Smithsonian       0
Remarks                                    4752
Wildlife: Size                                0
Conditions: Sky                               0
Wildlife: Species                             0
Pilot warned of birds or wildlife?            0
Cost: Total $                                 0
Feet above ground                             0
Number of people injured                      0
Is Aircraft Large?                            0
dtype: int64

In [252]:
birdspecies_filter[birdspecies_filter['Aircraft: Make/Model'] == 'CITATION MUSTANG 510']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
16197,JOE FOSS FIELD ARPT,< 1000 ft,CITATION MUSTANG 510,2 to 10,4,Precautionary Landing,3/10/2009,Caused damage,NaN,BUSINESS,...,False,BIRD REPTD AS BLUE GOOSE. DMG TO LWR L ENG COW...,Large,Overcast,Snow goose,N,31624,500,0,No
18239,HOUSTON-HOBBY,< 1000 ft,CITATION MUSTANG 510,1,1,None,9/17/2009,No damage,NaN,BUSINESS,...,False,"PIGEON SIZE BIRD. ON SHORT FINAL RWY 35, A/C I...",Small,Some Cloud,Unknown bird - small,N,369,200,0,No
20427,OAKLAND COUNTY INTL,< 1000 ft,CITATION MUSTANG 510,1,1,None,7/14/2010,No damage,NaN,BUSINESS,...,False,"UNKNOWN SMALL BIRD, PERHAPS A SWALLOW. LEFT SM...",Small,Some Cloud,Unknown bird - small,N,0,10,0,No
20492,BOB HOPE ARPT,< 1000 ft,CITATION MUSTANG 510,1,1,None,7/19/2010,No damage,NaN,BUSINESS,...,False,T/O ROLL ON RWY 15 WHEN REPT OF HITTING A BIRD...,Small,Overcast,Unknown bird - small,N,0,100,0,No
20895,HAGERSTOWN REGIONAL,< 1000 ft,CITATION MUSTANG 510,1,1,None,8/13/2010,No damage,NaN,BUSINESS,...,False,ARPT OPS FOUND CARCASS DURING ROUTINE RWY CK A...,Small,Overcast,American kestrel,N,0,0,0,No

In [253]:
citationmustang510_rows = birdspecies_filter[birdspecies_filter['Aircraft: Make/Model'] == 'CITATION MUSTANG 510']

# Fill NaN values in the 'Aircraft: Number of engines?' column for the filtered rows with the specified value (e.g., 8)
citationmustang510_rows['Aircraft: Number of engines?'].fillna(2, inplace=True)

# Assign the filled values back to the original DataFrame using loc
birdspecies_filter.loc[birdspecies_filter['Aircraft: Make/Model'] == 'CITATION MUSTANG 510', 'Aircraft: Number of engines?'] = citationmustang510_rows['Aircraft: Number of engines?']

# Display the updated DataFrame
print(birdspecies_filter)

                           Airport: Name Altitude bin Aircraft: Make/Model  \
0                       KANSAS CITY INTL    < 1000 ft                MD-80
1      CINCINNATI MUNI ARPT-LUNKEN FIELD    < 1000 ft          CITATION II
2                             MIAMI INTL    > 1000 ft              DA-2000
3            SOUTHWEST FLORIDA INTL ARPT    < 1000 ft           HAWKER 800
4                         NASHVILLE INTL    < 1000 ft            B-737-400
...                                  ...          ...                  ...
25198                       ORLANDO INTL    < 1000 ft                A-321
25199                  REDDING MUNICIPAL    > 1000 ft              EMB-120
25200    DETROIT METRO WAYNE COUNTY ARPT    < 1000 ft            B-757-200
25201       GEORGE BUSH INTERCONTINENTAL    < 1000 ft              EMB-145
25202       ABRAHAM LINCOLN CAPITAL ARPT    < 1000 ft            B-737-400

      Wildlife: Number struck  Wildlife: Number Struck Actual  \
0                   11 to 100                              54
1                           1                               1
2                           1                               1
3                           1                               1
4                           1                               1
...                       ...                             ...
25198                       1                               1
25199                       1                               1
25200                       1                               1
25201                 2 to 10                               6
25202                       1                               1

      Effect: Impact to flight  FlightDate Effect: Indicated Damage  \
0                         None    1/2/2000                No damage
1                         None    1/2/2000                No damage
2                         None    1/2/2000                No damage
3                         None    1/2/2000            Caused damage
4                         None    1/3/2000                No damage
...                        ...         ...                      ...
25198                     None  12/30/2011                No damage
25199                     None  12/30/2011                No damage
25200                     None  12/31/2011                No damage
25201                     None  12/31/2011                No damage
25202                     None  12/31/2011            Caused damage

       Aircraft: Number of engines? Aircraft: Airline/Operator  ...  \
0                               2.0       TRANS WORLD AIRLINES  ...
1                               2.0                   BUSINESS  ...
2                               2.0                   BUSINESS  ...
3                               2.0                   BUSINESS  ...
4                               2.0                US AIRWAYS*  ...
...                             ...                        ...  ...
25198                           2.0                 US AIRWAYS  ...
25199                           2.0           SKYWEST AIRLINES  ...
25200                           2.0            DELTA AIR LINES  ...
25201                           2.0         ATLANTIC SOUTHEAST  ...
25202                           2.0               XTRA AIRWAYS  ...

      Remains of wildlife sent to Smithsonian  \
0                                       False
1                                       False
2                                       False
3                                       False
4                                       False
...                                       ...
25198                                   False
25199                                   False
25200                                   False
25201                                   False
25202                                   False

                                                 Remarks Wildlife: Size  \
0                                                    NaN          Large
1                                                    NaN          Small
2                                                    NaN         Medium
3      SUSPECT GULL. HEARD THUMP ON APCH BUT NO ABNRM...         Medium
4                                                    NaN          Small
...                                                  ...            ...
25198                                                NaN          Small
25199                                DUCK? NO DMG REPTD.          Large
25200  PILOTS REPORT STRIKING UNKNOWN BIRD ON RWY 21L...         Medium
25201                                                NaN          Small
25202  HIT CENTER OF RADOME, CAVING IN ABOUT 12". RAD...         Medium

       Conditions: Sky      Wildlife: Species  \
0             No Cloud           Canada goose
1             Overcast   Unknown bird - small
2             No Cloud  Unknown bird - medium
3             No Cloud  Unknown bird - medium
4           Some Cloud   Unknown bird - small
...                ...                    ...
25198       Some Cloud           Tree swallow
25199         Overcast   Unknown bird - large
25200       Some Cloud  Unknown bird - medium
25201         Overcast   Unknown bird - small
25202         No Cloud        Red-tailed hawk

      Pilot warned of birds or wildlife? Cost: Total $ Feet above ground  \
0                                      N             0               350
1                                      N             0                 0
2                                      Y             0              2000
3                                      Y        120273               200
4                                      Y             0               800
...                                  ...           ...               ...
25198                                  Y             0                 0
25199                                  N             0              1500
25200                                  Y             0                 0
25201                                  Y             0                 0
25202                                  N             0                 0

      Number of people injured Is Aircraft Large?
0                            0                 No
1                            0                 No
2                            0                 No
3                            0                 No
4                            0                Yes
...                        ...                ...
25198                        0                 No
25199                        0                 No
25200                        0                Yes
25201                        0                 No
25202                        0                Yes

[25203 rows x 24 columns]

C:\Users\HP\AppData\Local\Temp\ipykernel_17440\1281406745.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  citationmustang510_rows['Aircraft: Number of engines?'].fillna(2, inplace=True)

In [257]:
birdspecies_filter[birdspecies_filter['Aircraft: Make/Model'] == 'GRUMMAN S-2 TRACKER']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
17446,NEVADA COUNTY AIR PARK,< 1000 ft,GRUMMAN S-2 TRACKER,1,1,None,7/25/2009,Caused damage,NaN,BUSINESS,...,False,PILOT SAW 2 KILLDEER ON BASE TO FINAL AND TRIE...,Small,No Cloud,Killdeer,N,263533,320,0,No
23556,UKIAH MUNICIPAL ARPT,< 1000 ft,GRUMMAN S-2 TRACKER,1,1,None,7/22/2011,No damage,NaN,GOVERNMENT,...,False,HIT FLAP HINGE.,Small,No Cloud,Unknown bird - small,N,0,0,0,No

In [258]:
grummans2tracker_rows = birdspecies_filter[birdspecies_filter['Aircraft: Make/Model'] == 'GRUMMAN S-2 TRACKER']

# Fill NaN values in the 'Aircraft: Number of engines?' column for the filtered rows with the specified value (e.g., 8)
grummans2tracker_rows['Aircraft: Number of engines?'].fillna(2, inplace=True)

# Assign the filled values back to the original DataFrame using loc
birdspecies_filter.loc[birdspecies_filter['Aircraft: Make/Model'] == 'GRUMMAN S-2 TRACKER', 'Aircraft: Number of engines?'] = grummans2tracker_rows['Aircraft: Number of engines?']

# Display the updated DataFrame
print(birdspecies_filter)

                           Airport: Name Altitude bin Aircraft: Make/Model  \
0                       KANSAS CITY INTL    < 1000 ft                MD-80
1      CINCINNATI MUNI ARPT-LUNKEN FIELD    < 1000 ft          CITATION II
2                             MIAMI INTL    > 1000 ft              DA-2000
3            SOUTHWEST FLORIDA INTL ARPT    < 1000 ft           HAWKER 800
4                         NASHVILLE INTL    < 1000 ft            B-737-400
...                                  ...          ...                  ...
25198                       ORLANDO INTL    < 1000 ft                A-321
25199                  REDDING MUNICIPAL    > 1000 ft              EMB-120
25200    DETROIT METRO WAYNE COUNTY ARPT    < 1000 ft            B-757-200
25201       GEORGE BUSH INTERCONTINENTAL    < 1000 ft              EMB-145
25202       ABRAHAM LINCOLN CAPITAL ARPT    < 1000 ft            B-737-400

      Wildlife: Number struck  Wildlife: Number Struck Actual  \
0                   11 to 100                              54
1                           1                               1
2                           1                               1
3                           1                               1
4                           1                               1
...                       ...                             ...
25198                       1                               1
25199                       1                               1
25200                       1                               1
25201                 2 to 10                               6
25202                       1                               1

      Effect: Impact to flight  FlightDate Effect: Indicated Damage  \
0                         None    1/2/2000                No damage
1                         None    1/2/2000                No damage
2                         None    1/2/2000                No damage
3                         None    1/2/2000            Caused damage
4                         None    1/3/2000                No damage
...                        ...         ...                      ...
25198                     None  12/30/2011                No damage
25199                     None  12/30/2011                No damage
25200                     None  12/31/2011                No damage
25201                     None  12/31/2011                No damage
25202                     None  12/31/2011            Caused damage

       Aircraft: Number of engines? Aircraft: Airline/Operator  ...  \
0                               2.0       TRANS WORLD AIRLINES  ...
1                               2.0                   BUSINESS  ...
2                               2.0                   BUSINESS  ...
3                               2.0                   BUSINESS  ...
4                               2.0                US AIRWAYS*  ...
...                             ...                        ...  ...
25198                           2.0                 US AIRWAYS  ...
25199                           2.0           SKYWEST AIRLINES  ...
25200                           2.0            DELTA AIR LINES  ...
25201                           2.0         ATLANTIC SOUTHEAST  ...
25202                           2.0               XTRA AIRWAYS  ...

      Remains of wildlife sent to Smithsonian  \
0                                       False
1                                       False
2                                       False
3                                       False
4                                       False
...                                       ...
25198                                   False
25199                                   False
25200                                   False
25201                                   False
25202                                   False

                                                 Remarks Wildlife: Size  \
0                                                    NaN          Large
1                                                    NaN          Small
2                                                    NaN         Medium
3      SUSPECT GULL. HEARD THUMP ON APCH BUT NO ABNRM...         Medium
4                                                    NaN          Small
...                                                  ...            ...
25198                                                NaN          Small
25199                                DUCK? NO DMG REPTD.          Large
25200  PILOTS REPORT STRIKING UNKNOWN BIRD ON RWY 21L...         Medium
25201                                                NaN          Small
25202  HIT CENTER OF RADOME, CAVING IN ABOUT 12". RAD...         Medium

       Conditions: Sky      Wildlife: Species  \
0             No Cloud           Canada goose
1             Overcast   Unknown bird - small
2             No Cloud  Unknown bird - medium
3             No Cloud  Unknown bird - medium
4           Some Cloud   Unknown bird - small
...                ...                    ...
25198       Some Cloud           Tree swallow
25199         Overcast   Unknown bird - large
25200       Some Cloud  Unknown bird - medium
25201         Overcast   Unknown bird - small
25202         No Cloud        Red-tailed hawk

      Pilot warned of birds or wildlife? Cost: Total $ Feet above ground  \
0                                      N             0               350
1                                      N             0                 0
2                                      Y             0              2000
3                                      Y        120273               200
4                                      Y             0               800
...                                  ...           ...               ...
25198                                  Y             0                 0
25199                                  N             0              1500
25200                                  Y             0                 0
25201                                  Y             0                 0
25202                                  N             0                 0

      Number of people injured Is Aircraft Large?
0                            0                 No
1                            0                 No
2                            0                 No
3                            0                 No
4                            0                Yes
...                        ...                ...
25198                        0                 No
25199                        0                 No
25200                        0                Yes
25201                        0                 No
25202                        0                Yes

[25203 rows x 24 columns]

C:\Users\HP\AppData\Local\Temp\ipykernel_17440\2061287399.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grummans2tracker_rows['Aircraft: Number of engines?'].fillna(2, inplace=True)

In [266]:
# Assuming your DataFrame is named birdspecies_filter

# Step 1: Filter the DataFrame for rows where 'Number of Engines' column has NaN values
nan_engine_rows = birdspecies_filter[birdspecies_filter['Aircraft: Number of engines?'].isnull()]

# Step 2: Display the 'Aircraft Model' column for the filtered rows
print(nan_engine_rows['Aircraft: Make/Model'])

33           F-15E
374        KC-135R
451          C-17A
582         AT-38B
598         AT-38B
           ...
24333         T-38
24580        HU-25
24726    PA-31-350
24776       F/A-18
25086        DA-40
Name: Aircraft: Make/Model, Length: 93, dtype: object

In [268]:
nan_engine_rows['Aircraft: Make/Model'].value_counts()

C-17A                 15
AT-38B                 8
PA-31-350              6
ECLIPSE 500            5
A-10A                  5
CESSNA UNKN            4
BD-700                 4
KC-135R                4
T-38                   4
HOMEBUILT              3
HU-25                  3
SA227 DC METRO 23      2
C-21A                  2
HAWKER 900             2
B-737-600              2
HC-130                 1
F-15E                  1
T-38N                  1
CRJ-900                1
FLIGHT DESIGN CTSW     1
CL-RJ705               1
B-787-800              1
F/A-18                 1
LOCKHEED P3A           1
AMD ALARUS CH2000      1
CESSNA LC-41           1
MISC - OTHER           1
CL-215                 1
CANADAIR               1
E-8C                   1
F-15C                  1
T-1A                   1
F-16D                  1
F-16C                  1
B-1B                   1
C-130E                 1
MC-130H                1
GRUMMAN                1
DA-40                  1
Name: Aircraft: Make/Model, dtype: int64

In [272]:
birdspecies_filter.to_csv(r'D:\UM internship\Bird Strike\birdstrike_filterspecies_new.csv')