In [2]:
import pandas as pd
import numpy as np

In [3]:
URL = r"D:\UM internship\Bird Strike\birdstrike_filterspecies_new.csv"
df = pd.read_csv(URL)
df.head()

,Unnamed: 0,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
0,0,KANSAS CITY INTL,< 1000 ft,MD-80,11 to 100,54,None,1/2/2000,No damage,2.0,...,False,NaN,Large,No Cloud,Canada goose,N,0,350,0,No
1,1,CINCINNATI MUNI ARPT-LUNKEN FIELD,< 1000 ft,CITATION II,1,1,None,1/2/2000,No damage,2.0,...,False,NaN,Small,Overcast,Unknown bird - small,N,0,0,0,No
2,2,MIAMI INTL,> 1000 ft,DA-2000,1,1,None,1/2/2000,No damage,2.0,...,False,NaN,Medium,No Cloud,Unknown bird - medium,Y,0,2000,0,No
3,3,SOUTHWEST FLORIDA INTL ARPT,< 1000 ft,HAWKER 800,1,1,None,1/2/2000,Caused damage,2.0,...,False,SUSPECT GULL. HEARD THUMP ON APCH BUT NO ABNRM...,Medium,No Cloud,Unknown bird - medium,Y,120273,200,0,No
4,4,NASHVILLE INTL,< 1000 ft,B-737-400,1,1,None,1/3/2000,No damage,2.0,...,False,NaN,Small,Some Cloud,Unknown bird - small,Y,0,800,0,Yes

In [4]:
df.drop('Unnamed: 0', axis = 1, inplace = True)

In [6]:
df1 = df.copy()

In [7]:
df1

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
0,KANSAS CITY INTL,< 1000 ft,MD-80,11 to 100,54,None,1/2/2000,No damage,2.0,TRANS WORLD AIRLINES,...,False,NaN,Large,No Cloud,Canada goose,N,0,350,0,No
1,CINCINNATI MUNI ARPT-LUNKEN FIELD,< 1000 ft,CITATION II,1,1,None,1/2/2000,No damage,2.0,BUSINESS,...,False,NaN,Small,Overcast,Unknown bird - small,N,0,0,0,No
2,MIAMI INTL,> 1000 ft,DA-2000,1,1,None,1/2/2000,No damage,2.0,BUSINESS,...,False,NaN,Medium,No Cloud,Unknown bird - medium,Y,0,2000,0,No
3,SOUTHWEST FLORIDA INTL ARPT,< 1000 ft,HAWKER 800,1,1,None,1/2/2000,Caused damage,2.0,BUSINESS,...,False,SUSPECT GULL. HEARD THUMP ON APCH BUT NO ABNRM...,Medium,No Cloud,Unknown bird - medium,Y,120273,200,0,No
4,NASHVILLE INTL,< 1000 ft,B-737-400,1,1,None,1/3/2000,No damage,2.0,US AIRWAYS*,...,False,NaN,Small,Some Cloud,Unknown bird - small,Y,0,800,0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25198,ORLANDO INTL,< 1000 ft,A-321,1,1,None,12/30/2011,No damage,2.0,US AIRWAYS,...,False,NaN,Small,Some Cloud,Tree swallow,Y,0,0,0,No
25199,REDDING MUNICIPAL,> 1000 ft,EMB-120,1,1,None,12/30/2011,No damage,2.0,SKYWEST AIRLINES,...,False,DUCK? NO DMG REPTD.,Large,Overcast,Unknown bird - large,N,0,1500,0,No
25200,DETROIT METRO WAYNE COUNTY ARPT,< 1000 ft,B-757-200,1,1,None,12/31/2011,No damage,2.0,DELTA AIR LINES,...,False,PILOTS REPORT STRIKING UNKNOWN BIRD ON RWY 21L...,Medium,Some Cloud,Unknown bird - medium,Y,0,0,0,Yes
25201,GEORGE BUSH INTERCONTINENTAL,< 1000 ft,EMB-145,2 to 10,6,None,12/31/2011,No damage,2.0,ATLANTIC SOUTHEAST,...,False,NaN,Small,Overcast,Unknown bird - small,Y,0,0,0,No
25202,ABRAHAM LINCOLN CAPITAL ARPT,< 1000 ft,B-737-400,1,1,None,12/31/2011,Caused damage,2.0,XTRA AIRWAYS,...,False,"HIT CENTER OF RADOME, CAVING IN ABOUT 12"". RAD...",Medium,No Cloud,Red-tailed hawk,N,0,0,0,Yes

In [11]:
df1.isnull().sum()

Airport: Name                                 0
Altitude bin                                  0
Aircraft: Make/Model                          0
Wildlife: Number struck                       0
Wildlife: Number Struck Actual                0
Effect: Impact to flight                      0
FlightDate                                    0
Effect: Indicated Damage                      0
Aircraft: Number of engines?                 93
Aircraft: Airline/Operator                    0
Origin State                                449
When: Phase of flight                         0
Conditions: Precipitation                     0
Remains of wildlife collected?                0
Remains of wildlife sent to Smithsonian       0
Remarks                                    4752
Wildlife: Size                                0
Conditions: Sky                               0
Wildlife: Species                             0
Pilot warned of birds or wildlife?            0
Cost: Total $                                 0
Feet above ground                             0
Number of people injured                      0
Is Aircraft Large?                            0
dtype: int64

In [34]:
df1.dropna(subset= ['Aircraft: Number of engines?', 'Origin State'], inplace = True)

In [35]:
df1.isnull().sum()

Airport: Name                                 0
Altitude bin                                  0
Aircraft: Make/Model                          0
Wildlife: Number struck                       0
Wildlife: Number Struck Actual                0
Effect: Impact to flight                      0
FlightDate                                    0
Effect: Indicated Damage                      0
Aircraft: Number of engines?                  0
Aircraft: Airline/Operator                    0
Origin State                                  0
When: Phase of flight                         0
Conditions: Precipitation                     0
Remains of wildlife collected?                0
Remains of wildlife sent to Smithsonian       0
Remarks                                    4620
Wildlife: Size                                0
Conditions: Sky                               0
Wildlife: Species                             0
Pilot warned of birds or wildlife?            0
Cost: Total $                                 0
Feet above ground                             0
Number of people injured                      0
Is Aircraft Large?                            0
dtype: int64

In [37]:
df1.drop(['Remarks'], axis = 1, inplace = True)

In [40]:
df1.isnull().sum()

Airport: Name                              0
Altitude bin                               0
Aircraft: Make/Model                       0
Wildlife: Number struck                    0
Wildlife: Number Struck Actual             0
Effect: Impact to flight                   0
FlightDate                                 0
Effect: Indicated Damage                   0
Aircraft: Number of engines?               0
Aircraft: Airline/Operator                 0
Origin State                               0
When: Phase of flight                      0
Conditions: Precipitation                  0
Remains of wildlife collected?             0
Remains of wildlife sent to Smithsonian    0
Wildlife: Size                             0
Conditions: Sky                            0
Wildlife: Species                          0
Pilot warned of birds or wildlife?         0
Cost: Total $                              0
Feet above ground                          0
Number of people injured                   0
Is Aircraft Large?                         0
dtype: int64

In [41]:
df1.to_csv(r'D:\UM internship\Bird Strike\cleaned_data_with_filterspecies.csv', index = False)