In [1]:
import pandas as pd
import numpy as np

In [2]:
URL = r"D:\UM internship\Bird Strike\birdnew.csv"

birdstrike_new = pd.read_csv(URL)

In [12]:
birdstrike_new[birdstrike_new['Aircraft: Make/Model'] == 'C-680']

,Unnamed: 0,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
2969,2971,DUPAGE AIRPORT,> 1000 ft,C-680,2 to 10,9,None,2009-07-28,No damage,2,...,False,PER NOTAM,Small,Some Cloud,Unknown bird - small,Y,0,1200.0,0,No
3444,3446,MORRISTOWN MUNICIPAL ARPT,< 1000 ft,C-680,2 to 10,8,None,2010-07-12,No damage,2,...,False,A/C REPTD FLYING THRU A SMALL FLOCK OF BIRDS D...,Small,Overcast,Barn swallow,Y,0,0.0,0,No
3540,3542,RICKENBACKER INTL,< 1000 ft,C-680,2 to 10,2,None,2010-08-11,No damage,NaN,...,False,PILOT REPTS ONE STRUCK WINDSCREEN. THREE CARCA...,Small,Overcast,Purple martin,Y,0,100.0,0,No
3666,3668,ADDINGTON FIELD ARPT,< 1000 ft,C-680,2 to 10,7,None,2010-09-27,No damage,2,...,False,HIT L ENG PYLON JUST BEFORE TOUCHDOWN. SMUDGES...,Large,Some Cloud,Wild turkey,N,0,10.0,0,No
4292,4296,OAKLAND COUNTY INTL,< 1000 ft,C-680,2 to 10,6,None,2011-11-30,No damage,2,...,False,NO DMG NOTED. MX WILL INSPECT ENG AND PITOT TU...,Small,Some Cloud,Unknown bird - small,N,0,10.0,0,No
13814,13844,CHICAGO MIDWAY INTL ARPT,< 1000 ft,C-680,1,1,None,2006-11-03,No damage,NaN,...,False,FOUND FEATHES AND OTHER STRIKE EVIDENCE ON L W...,Small,No Cloud,Unknown bird - small,N,0,50.0,0,No
14726,14758,MINNEAPOLIS-ST PAUL INTL,< 1000 ft,C-680,1,1,None,2007-06-27,No damage,NaN,...,False,ATIS WARNING. ATC ADZ A CESSNA CITATION REPTD ...,Small,Some Cloud,Cliff swallow,Y,0,0.0,0,No
14918,14950,TETERBORO AIRPORT,< 1000 ft,C-680,1,1,None,2007-07-22,No damage,NaN,...,False,BIRD STRUCK ON RWY 1 AND TWY G.,Small,No Cloud,European starling,Y,0,0.0,0,No
15631,15668,TETERBORO AIRPORT,< 1000 ft,C-680,1,1,None,2007-10-20,No damage,NaN,...,False,ROC NOTIFIED SPOIKE W/E.F.,Small,No Cloud,Unknown bird - small,Y,0,0.0,0,No
16001,16040,CHICAGO O'HARE INTL ARPT,< 1000 ft,C-680,1,1,None,2008-02-28,Caused damage,NaN,...,False,DID NOT SEE ANY DMG ON A/C WHILE AT ORD. WHEN ...,Medium,Some Cloud,Red-tailed hawk,N,11905,3.0,0,No
16457,16501,RALEIGH-DURHAM INTL,> 1000 ft,C-680,1,1,None,2008-06-08,No damage,2,...,False,NO KNOWN DMG,Small,Some Cloud,Unknown bird - small,Y,0,2000.0,0,No
16501,16546,TETERBORO AIRPORT,< 1000 ft,C-680,1,1,None,2008-06-17,No damage,2,...,True,ID BY SMITHSONIAN. REPTD BIRDSTRIKE. ARFF RESP...,Small,Some Cloud,Savannah sparrow,Y,0,0.0,0,No
16502,16547,CHINO AIRPORT,< 1000 ft,C-680,1,1,None,2008-06-18,No damage,2,...,False,"JUST PRIOR TO T/D, A FEW BIRDS TOOK FLIGHT ACR...",Small,No Cloud,Unknown bird - small,N,0,20.0,0,No
16922,16968,MORRISTOWN MUNICIPAL ARPT,< 1000 ft,C-680,1,1,None,2008-08-10,No damage,2,...,True,"ID BY SMITHSONIAN, FAA 2595. PILOT REPTD HITTI...",Small,Overcast,Barn swallow,Y,0,0.0,0,No
17406,17453,TETERBORO AIRPORT,< 1000 ft,C-680,1,1,Aborted Take-off,2008-10-11,No damage,2,...,False,FOUND ON RWY 1 AND TWY J.,Small,No Cloud,Upland sandpiper,Y,0,0.0,0,No
17635,17683,ADDISON,< 1000 ft,C-680,1,1,None,2008-11-19,No damage,2,...,False,NaN,Small,No Cloud,Mourning dove,Y,0,0.0,0,No
17808,17856,WESTCHESTER COUNTY ARPT,< 1000 ft,C-680,1,1,Precautionary Landing,2009-01-16,Caused damage,2,...,False,"HIT A BIRD ON CLIMB OVER NEW CASTLE, OUTSIDE A...",Small,Some Cloud,Unknown bird - small,Y,0,700.0,0,No
18805,18855,WESTCHESTER COUNTY ARPT,< 1000 ft,C-680,1,1,None,2009-07-07,No damage,2,...,False,CREW REPTD STRIKING THE BIRD BUT DID NOT INDIC...,Small,Some Cloud,Barn swallow,Y,0,0.0,0,No
20376,20439,FORT LAUDERDALE EXECUTIVE ARPT,< 1000 ft,C-680,1,1,None,2009-11-29,No damage,2,...,False,ATIS WARNING. PILOT REPTD NO DMG TO A/C.,Small,Some Cloud,Unknown bird - small,Y,0,50.0,0,No
21427,21505,WILLOW RUN ARPT,< 1000 ft,C-680,1,1,None,2010-07-03,No damage,NaN,...,False,NO DMG.,Small,No Cloud,Unknown bird - small,N,0,0.0,0,No
21520,21598,GOLDEN TRIANGLE REGIONAL,< 1000 ft,C-680,1,1,None,2010-07-12,No damage,2,...,False,NaN,Small,Some Cloud,Unknown bird - small,N,0,20.0,0,No
21972,22055,TOLEDO EXPRESS ARPT,< 1000 ft,C-680,1,1,None,2010-08-19,No damage,2,...,False,NaN,Small,No Cloud,Unknown bird - small,N,0,50.0,0,No
23001,23092,BRADLEY INTL,< 1000 ft,C-680,1,1,None,2010-12-26,No damage,2,...,False,A/C INSPECTED BY MESA CITATION SERVICE. NO IMP...,Small,Overcast,Unknown bird - small,N,0,0.0,0,No
23283,23380,CHARLOTTESVILLE-ALBEMARLE ARPT,< 1000 ft,C-680,1,1,None,2011-04-01,No damage,2,...,False,NO DMG. BIRDSTRIKE OCCURRED OUTSIDE THE NACELL...,Medium,Some Cloud,Gulls,N,0,0.0,0,No
25132,25256,SUGAR LAND REGIONAL ARPT,< 1000 ft,C-680,1,1,Other,2011-10-25,No damage,2,...,True,"ID BY SMITHSONIAN. FAA 6862, WHOLE FEATHER. BI...",Small,Some Cloud,Mourning dove,N,500,0.0,0,No

In [15]:
selected_rows = [2969,3444, 3540, 3666, 4292, 13814, 14726, 14918,15631, 16001, 21427, 21520]
selected_column = 'Aircraft: Number of engines?'

subset = birdstrike_new.loc[selected_rows, selected_column]

filled_data = subset.bfill()

In [16]:
filled_data

2969     2
3444     2
3540     2
3666     2
4292     2
13814    2
14726    2
14918    2
15631    2
16001    2
21427    2
21520    2
Name: Aircraft: Number of engines?, dtype: object

In [18]:
birdstrike_new.loc[selected_rows, selected_column] = filled_data

In [19]:
birdstrike_new.isnull().sum()

Unnamed: 0                                    0
Airport: Name                                 0
Altitude bin                                  0
Aircraft: Make/Model                          0
Wildlife: Number struck                       0
Wildlife: Number Struck Actual                0
Effect: Impact to flight                      0
FlightDate                                    0
Effect: Indicated Damage                      0
Aircraft: Number of engines?                227
Aircraft: Airline/Operator                    0
Origin State                                449
When: Phase of flight                         0
Conditions: Precipitation                     0
Remains of wildlife collected?                0
Remains of wildlife sent to Smithsonian       0
Remarks                                    4761
Wildlife: Size                                0
Conditions: Sky                               0
Wildlife: Species                             0
Pilot warned of birds or wildlife?            0
Cost: Total $                                 0
Feet above ground                             0
Number of people injured                      0
Is Aircraft Large?                            0
dtype: int64

In [26]:
birdstrike_new[birdstrike_new['Aircraft: Number of engines?'] == 'C']

,Unnamed: 0,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
6652,6664,MORGANTOWN MUNICIPAL ARPT,> 1000 ft,RKWLTRBO 690,1,1,None,2001-11-05,No damage,C,...,False,PILOT ADZ NO DMG. INFO RELAYED TO CKB THRU MGW...,Medium,No Cloud,Unknown bird - medium,N,0,4000.0,0,No

In [28]:
birdstrike_new.at[6652,'Aircraft: Number of engines?'] = 2

In [30]:
birdstrike_new['Aircraft: Number of engines?'].unique()

array(['2', '3', '4', nan, '1', 2], dtype=object)

In [42]:
birdstrike_new[birdstrike_new['Aircraft: Make/Model'] == 'B-747-8 SERIES']

,Unnamed: 0,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
3574,3576,COLORADO SPRINGS MUNICIPAL,< 1000 ft,B-747-8 SERIES,2 to 10,4,None,2010-08-21,No damage,4,...,False,TWO-THREE SPARROWS (SOMEWHAT INTACT) AND ONE H...,Small,No Cloud,Sparrows,N,0,0.0,0,No
23032,23124,BOEING FIELD K C INT,< 1000 ft,B-747-8 SERIES,1,1,None,2011-01-03,Caused damage,NaN,...,True,ID BY SMITHSONIAN. BOTH SAMPLES WERE SAME ID. ...,Medium,Some Cloud,Herring gull,N,0,0.0,0,No

In [49]:
birdstrike_new.at[23032, 'Aircraft: Number of engines?'] = 4

In [50]:
birdstrike_new[birdstrike_new['Aircraft: Make/Model'] == 'B-747-8 SERIES']

,Unnamed: 0,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
3574,3576,COLORADO SPRINGS MUNICIPAL,< 1000 ft,B-747-8 SERIES,2 to 10,4,None,2010-08-21,No damage,4,...,False,TWO-THREE SPARROWS (SOMEWHAT INTACT) AND ONE H...,Small,No Cloud,Sparrows,N,0,0.0,0,No
23032,23124,BOEING FIELD K C INT,< 1000 ft,B-747-8 SERIES,1,1,None,2011-01-03,Caused damage,4,...,True,ID BY SMITHSONIAN. BOTH SAMPLES WERE SAME ID. ...,Medium,Some Cloud,Herring gull,N,0,0.0,0,No

In [53]:
birdstrike_new.to_csv(r'D:\UM internship\Bird Strike\birdnew.csv')