In [5]:
import pandas as pd
import numpy as np

In [6]:
URL = r"D:\UM internship\Bird Strike\bird_strike_URMproject.csv"

bird_strike2 = pd.read_csv(URL)

In [22]:
bird_strike2.drop('Unnamed: 0', axis = 1, inplace = True)

In [23]:
bird_strike2

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
0,LAGUARDIA NY,> 1000 ft,B-737-400,Over 100,859,Engine Shut Down,2000-11-23,Caused damage,2.0,US AIRWAYS*,...,Climb,None,Medium,No Cloud,Unknown bird - medium,N,30736,1500.0,0,Yes
1,DALLAS/FORT WORTH INTL ARPT,< 1000 ft,MD-80,Over 100,424,None,2001-07-25,Caused damage,2.0,AMERICAN AIRLINES,...,Landing Roll,None,Small,Some Cloud,Rock pigeon,Y,0,0.0,0,No
2,LAKEFRONT AIRPORT,< 1000 ft,C-500,Over 100,261,None,2001-09-14,No damage,2.0,BUSINESS,...,Approach,None,Small,No Cloud,European starling,N,0,50.0,0,No
3,SEATTLE-TACOMA INTL,< 1000 ft,B-737-400,Over 100,806,Precautionary Landing,2002-09-05,No damage,2.0,ALASKA AIRLINES,...,Climb,None,Small,Some Cloud,European starling,Y,0,50.0,0,Yes
4,NORFOLK INTL,< 1000 ft,CL-RJ100/200,Over 100,942,None,2003-06-23,No damage,2.0,COMAIR AIRLINES,...,Approach,None,Small,No Cloud,European starling,N,0,50.0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25424,SACRAMENTO INTL,< 1000 ft,B-737-700,1,1,None,2011-12-29,No damage,2.0,SOUTHWEST AIRLINES,...,Approach,None,Medium,No Cloud,Mallard,Y,0,10.0,0,Yes
25425,REDDING MUNICIPAL,> 1000 ft,EMB-120,1,1,None,2011-12-30,No damage,2.0,SKYWEST AIRLINES,...,Approach,Fog,Large,Overcast,Unknown bird - large,N,0,1500.0,0,No
25426,ORLANDO INTL,< 1000 ft,A-321,1,1,None,2011-12-30,No damage,2.0,US AIRWAYS,...,Landing Roll,None,Small,Some Cloud,Tree swallow,Y,0,0.0,0,No
25427,DETROIT METRO WAYNE COUNTY ARPT,< 1000 ft,B-757-200,1,1,None,2011-12-31,No damage,2.0,DELTA AIR LINES,...,Landing Roll,None,Medium,Some Cloud,Unknown bird - medium,Y,0,0.0,0,Yes
25428,ABRAHAM LINCOLN CAPITAL ARPT,< 1000 ft,B-737-400,1,1,None,2011-12-31,Caused damage,2.0,XTRA AIRWAYS,...,Take-off run,None,Medium,No Cloud,Red-tailed hawk,N,0,0.0,0,Yes

In [205]:
bird_strike2[pd.isnull(bird_strike2['Aircraft: Number of engines?'])].head(227)

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
42,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,2 to 10,10,None,2000-04-06,No damage,NaN,MILITARY,...,Approach,None,Medium,No Cloud,Unknown bird or bat,Y,0,1000.0,0,No
61,BARKSDALE AIR FORCE BASE ARPT,> 1000 ft,B-52H,2 to 10,9,None,2000-05-18,No damage,NaN,MILITARY,...,Approach,None,Small,No Cloud,Cape May warbler,Y,0,1200.0,0,No
210,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,2 to 10,5,None,2000-11-13,No damage,NaN,MILITARY,...,Approach,None,Small,No Cloud,American pipit,Y,7879,500.0,0,No
216,CHARLESTON AFB/INTL ARPT,> 1000 ft,C-17A,2 to 10,8,None,2000-11-29,No damage,NaN,MILITARY,...,Approach,None,Medium,No Cloud,Unknown bird or bat,Y,0,1600.0,0,No
220,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,B-52H,2 to 10,2,Precautionary Landing,2000-12-12,Caused damage,NaN,MILITARY,...,Climb,None,Medium,No Cloud,Gadwall,Y,458207,500.0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24957,ELLINGTON FIELD ARPT,< 1000 ft,T-38A,1,1,None,2011-10-07,No damage,NaN,GOVERNMENT,...,Take-off run,None,Small,No Cloud,Cliff swallow,N,0,0.0,0,No
25037,JOHN F KENNEDY INTL,< 1000 ft,CRJ-440,1,1,None,2011-10-16,No damage,NaN,PINNACLE,...,Landing Roll,None,Small,No Cloud,Short-eared owl,Y,0,0.0,0,No
25062,FORT LAUDERDALE EXECUTIVE ARPT,< 1000 ft,PA-31-350,1,1,None,2011-10-18,No damage,NaN,BUSINESS,...,Approach,None,Small,Overcast,American kestrel,N,0,20.0,0,No
25092,HONOLULU INTL ARPT,< 1000 ft,F/A-18,1,1,None,2011-10-22,No damage,NaN,HAWAIIAN AIR,...,Landing Roll,None,Small,No Cloud,Unknown bird - small,N,0,0.0,0,No
25347,KALAELOA ARPT JOHN RODGERS FIELD,< 1000 ft,DA-40,1,1,None,2011-11-30,No damage,NaN,BUSINESS,...,Taxi,None,Small,No Cloud,Zebra dove,N,0,0.0,0,No

In [28]:
filtered_data = bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'C-17A']
filtered_data

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
216,CHARLESTON AFB/INTL ARPT,> 1000 ft,C-17A,2 to 10,8,None,2000-11-29,No damage,NaN,MILITARY,...,Approach,None,Medium,No Cloud,Unknown bird or bat,Y,0,1600.0,0,No
242,CHARLESTON AFB/INTL ARPT,< 1000 ft,C-17A,2 to 10,10,None,2001-01-28,No damage,NaN,MILITARY,...,Approach,None,Medium,No Cloud,Unknown bird or bat,Y,0,400.0,0,No
247,CHARLESTON AFB/INTL ARPT,< 1000 ft,C-17A,2 to 10,8,None,2001-02-07,No damage,NaN,MILITARY,...,Take-off run,None,Medium,No Cloud,Unknown bird or bat,Y,0,0.0,0,No
297,CHARLESTON AFB/INTL ARPT,< 1000 ft,C-17A,2 to 10,9,None,2001-06-14,No damage,NaN,MILITARY,...,Take-off run,None,Small,No Cloud,Cattle egret,Y,4165,0.0,0,No
303,CHARLESTON AFB/INTL ARPT,< 1000 ft,C-17A,2 to 10,5,Precautionary Landing,2001-07-02,No damage,NaN,MILITARY,...,Climb,None,Medium,Some Cloud,Unknown bird or bat,Y,0,50.0,0,No
368,CHARLESTON AFB/INTL ARPT,< 1000 ft,C-17A,2 to 10,4,Aborted Take-off,2001-08-31,No damage,NaN,MILITARY,...,Take-off run,None,Small,No Cloud,Cattle egret,Y,0,0.0,0,No
375,CHARLESTON AFB/INTL ARPT,< 1000 ft,C-17A,2 to 10,9,Precautionary Landing,2001-09-04,No damage,NaN,MILITARY,...,Climb,Rain,Medium,Some Cloud,Unknown bird or bat,Y,0,0.0,0,No
579,CHARLESTON AFB/INTL ARPT,< 1000 ft,C-17A,2 to 10,9,None,2002-07-23,Caused damage,NaN,MILITARY,...,Take-off run,None,Small,Some Cloud,Mourning dove,Y,3803,0.0,0,No
706,CHARLESTON AFB/INTL ARPT,< 1000 ft,C-17A,2 to 10,2,None,2002-10-16,No damage,NaN,MILITARY,...,Climb,None,Medium,Some Cloud,Unknown bird or bat,Y,0,400.0,0,No
755,CHARLESTON AFB/INTL ARPT,< 1000 ft,C-17A,2 to 10,10,Precautionary Landing,2002-11-23,No damage,NaN,MILITARY,...,Climb,None,Medium,No Cloud,Unknown bird or bat,Y,0,300.0,0,No
5014,CHARLESTON AFB/INTL ARPT,< 1000 ft,C-17A,1,1,Precautionary Landing,2000-06-16,No damage,NaN,MILITARY,...,Approach,None,Medium,Some Cloud,Unknown bird or bat,Y,0,300.0,0,No
6571,CHARLESTON AFB/INTL ARPT,> 1000 ft,C-17A,1,1,Precautionary Landing,2001-10-07,No damage,NaN,MILITARY,...,Approach,None,Medium,Overcast,Unknown bird or bat,Y,0,2000.0,0,No
6836,CHARLESTON AFB/INTL ARPT,< 1000 ft,C-17A,1,1,Aborted Take-off,2002-03-21,No damage,NaN,MILITARY,...,Take-off run,Rain,Medium,Overcast,Unknown bird or bat,Y,0,0.0,0,No
7004,CHARLESTON AFB/INTL ARPT,> 1000 ft,C-17A,1,1,Precautionary Landing,2002-05-02,No damage,NaN,MILITARY,...,Approach,None,Medium,No Cloud,Unknown bird or bat,Y,0,2000.0,0,No
7921,CHARLESTON AFB/INTL ARPT,< 1000 ft,C-17A,1,1,Precautionary Landing,2002-10-28,No damage,NaN,MILITARY,...,Approach,None,Medium,No Cloud,Unknown bird or bat,Y,0,200.0,0,No

In [29]:
filtered_data = bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'T-38A']
filtered_data

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
257,SHEPPARD AIR FORCE BASE,> 1000 ft,T-38A,2 to 10,3,Precautionary Landing,2001-03-05,No damage,NaN,MILITARY,...,Approach,None,Medium,No Cloud,Unknown bird or bat,Y,1,1800.0,0,No
434,SHEPPARD AIR FORCE BASE,< 1000 ft,T-38A,2 to 10,9,Precautionary Landing,2001-11-06,No damage,NaN,MILITARY,...,Climb,None,Small,No Cloud,Common grackle,Y,0,400.0,0,No
4303,ELLINGTON FIELD ARPT,< 1000 ft,T-38A,2 to 10,9,None,2011-12-07,No damage,NaN,GOVERNMENT,...,Approach,None,Small,No Cloud,Unknown bird - small,N,0,15.0,0,No
5108,SHEPPARD AIR FORCE BASE,< 1000 ft,T-38A,1,1,None,2000-07-10,No damage,NaN,MILITARY,...,Take-off run,None,Medium,No Cloud,Unknown bird or bat,Y,21,2.0,0,No
5785,SHEPPARD AIR FORCE BASE,> 1000 ft,T-38A,1,1,Precautionary Landing,2001-01-20,No damage,NaN,MILITARY,...,Climb,None,Small,No Cloud,Horned lark,Y,21,2000.0,0,No
5796,SHEPPARD AIR FORCE BASE,> 1000 ft,T-38A,1,1,Precautionary Landing,2001-02-01,Caused damage,NaN,MILITARY,...,Approach,None,Medium,No Cloud,Pied-billed grebe,Y,39983,2800.0,0,No
5838,SHEPPARD AIR FORCE BASE,> 1000 ft,T-38A,1,1,Precautionary Landing,2001-03-05,No damage,NaN,MILITARY,...,Approach,None,Small,No Cloud,American robin,Y,1,1800.0,0,No
5923,SHEPPARD AIR FORCE BASE,< 1000 ft,T-38A,1,1,Precautionary Landing,2001-04-16,No damage,NaN,MILITARY,...,Take-off run,None,Small,Some Cloud,Upland sandpiper,Y,0,300.0,0,No
6093,SHEPPARD AIR FORCE BASE,< 1000 ft,T-38A,1,1,None,2001-06-14,No damage,NaN,MILITARY,...,Take-off run,None,Medium,No Cloud,Unknown bird or bat,Y,0,0.0,0,No
6309,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,T-38A,1,1,Precautionary Landing,2001-08-09,No damage,NaN,MILITARY,...,Climb,None,Small,No Cloud,American robin,Y,0,450.0,0,No
6555,SHEPPARD AIR FORCE BASE,< 1000 ft,T-38A,1,1,None,2001-10-04,No damage,NaN,MILITARY,...,Approach,None,Medium,No Cloud,Unknown bird or bat,Y,0,400.0,0,No
6655,SHEPPARD AIR FORCE BASE,< 1000 ft,T-38A,1,1,None,2001-11-06,No damage,NaN,MILITARY,...,Take-off run,None,Small,No Cloud,Mourning dove,Y,0,0.0,0,No
6845,SHEPPARD AIR FORCE BASE,< 1000 ft,T-38A,1,1,Precautionary Landing,2002-03-26,No damage,NaN,MILITARY,...,Approach,None,Small,No Cloud,Mourning dove,Y,19016,800.0,0,No
7068,SHEPPARD AIR FORCE BASE,< 1000 ft,T-38A,1,1,Aborted Take-off,2002-05-13,No damage,NaN,MILITARY,...,Take-off run,None,Small,No Cloud,Eastern meadowlark,Y,0,0.0,0,No
7228,SHEPPARD AIR FORCE BASE,< 1000 ft,T-38A,1,1,None,2002-06-19,No damage,NaN,MILITARY,...,Take-off run,None,Medium,No Cloud,Unknown bird or bat,Y,0,0.0,0,No
7420,SHEPPARD AIR FORCE BASE,< 1000 ft,T-38A,1,1,Precautionary Landing,2002-07-28,Caused damage,NaN,MILITARY,...,Approach,None,Medium,Some Cloud,Unknown bird or bat,Y,103955,500.0,0,No
7806,SHEPPARD AIR FORCE BASE,< 1000 ft,T-38A,1,1,Precautionary Landing,2002-10-03,No damage,NaN,MILITARY,...,Climb,None,Medium,No Cloud,Unknown bird or bat,Y,0,10.0,0,No
7842,EDWARDS AIR FORCE BASE,< 1000 ft,T-38A,1,1,Precautionary Landing,2002-10-10,No damage,NaN,MILITARY,...,Climb,None,Medium,No Cloud,Unknown bird or bat,Y,0,400.0,0,No
7843,SHEPPARD AIR FORCE BASE,< 1000 ft,T-38A,1,1,Aborted Take-off,2002-10-10,Caused damage,NaN,MILITARY,...,Climb,None,Medium,No Cloud,Unknown bird or bat,Y,127,0.0,0,No
9807,ELLINGTON FIELD ARPT,< 1000 ft,T-38A,1,1,Aborted Take-off,2004-06-27,Caused damage,NaN,GOVERNMENT,...,Take-off run,None,Small,Some Cloud,Barn owl,N,0,0.0,0,No
11121,ELLINGTON FIELD ARPT,< 1000 ft,T-38A,1,1,Other,2005-05-31,No damage,NaN,GOVERNMENT,...,Approach,None,Small,Overcast,Barn owl,N,0,3.0,0,No
13823,ELLINGTON FIELD ARPT,< 1000 ft,T-38A,1,1,None,2006-11-06,No damage,NaN,GOVERNMENT,...,Landing Roll,None,Small,Some Cloud,Unknown bird - small,Y,0,0.0,0,No
16897,ELLINGTON FIELD ARPT,< 1000 ft,T-38A,1,1,Other,2008-08-07,Caused damage,NaN,GOVERNMENT,...,Take-off run,None,Small,Some Cloud,Killdeer,Y,25391,0.0,0,No
17946,ELLINGTON FIELD ARPT,< 1000 ft,T-38A,1,1,None,2009-03-09,No damage,NaN,GOVERNMENT,...,Approach,None,Small,Some Cloud,Eastern meadowlark,N,0,38.0,0,No
18017,ELLINGTON FIELD ARPT,< 1000 ft,T-38A,1,1,None,2009-03-25,No damage,NaN,GOVERNMENT,...,Approach,None,Small,Some Cloud,Unknown bird - small,N,0,62.0,0,No
18937,ELLINGTON FIELD ARPT,< 1000 ft,T-38A,1,1,None,2009-07-17,No damage,NaN,GOVERNMENT,...,Approach,None,Small,Overcast,Barn swallow,Y,0,32.0,0,No
20647,ELLINGTON FIELD ARPT,> 1000 ft,T-38A,1,1,None,2010-03-04,No damage,NaN,GOVERNMENT,...,Approach,None,Medium,No Cloud,Unknown bird - medium,N,0,2200.0,0,No
24957,ELLINGTON FIELD ARPT,< 1000 ft,T-38A,1,1,None,2011-10-07,No damage,NaN,GOVERNMENT,...,Take-off run,None,Small,No Cloud,Cliff swallow,N,0,0.0,0,No

In [131]:
filtered_data = bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'CRJ-440']
filtered_data

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
1803,DETROIT METRO WAYNE COUNTY ARPT,< 1000 ft,CRJ-440,2 to 10,5,None,2006-07-18,No damage,NaN,PINNACLE,...,Landing Roll,None,Small,Some Cloud,Mourning dove,Y,0,0.0,0,No
1804,MEMPHIS INTL,< 1000 ft,CRJ-440,2 to 10,10,None,2006-07-18,No damage,NaN,PINNACLE,...,Landing Roll,None,Small,Some Cloud,Rock pigeon,N,0,0.0,0,No
2180,CLEVELAND-HOPKINS INTL ARPT,< 1000 ft,CRJ-440,2 to 10,9,None,2007-07-28,No damage,NaN,PINNACLE,...,Approach,None,Small,Some Cloud,Barn swallow,Y,0,50.0,0,No
2885,DETROIT METRO WAYNE COUNTY ARPT,< 1000 ft,CRJ-440,2 to 10,7,None,2009-06-18,No damage,NaN,PINNACLE,...,Landing Roll,None,Small,No Cloud,Horned lark,Y,0,0.0,0,No
2922,DETROIT METRO WAYNE COUNTY ARPT,< 1000 ft,CRJ-440,2 to 10,6,None,2009-07-12,No damage,NaN,PINNACLE,...,Landing Roll,None,Small,No Cloud,European starling,Y,0,0.0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21886,OUTAGAMIE COUNTY REGIONAL,< 1000 ft,CRJ-440,1,1,None,2010-08-11,No damage,NaN,PINNACLE,...,Landing Roll,None,Small,Some Cloud,Killdeer,N,0,0.0,0,No
22173,DETROIT METRO WAYNE COUNTY ARPT,< 1000 ft,CRJ-440,1,1,None,2010-09-03,No damage,NaN,PINNACLE,...,Take-off run,None,Medium,Some Cloud,Red-tailed hawk,Y,0,0.0,0,No
23646,DETROIT METRO WAYNE COUNTY ARPT,< 1000 ft,CRJ-440,1,1,None,2011-05-22,No damage,NaN,PINNACLE,...,Landing Roll,None,Small,Some Cloud,Unknown bird - small,Y,0,0.0,0,No
24281,QUAD CITY ARPT,< 1000 ft,CRJ-440,1,1,None,2011-08-06,No damage,NaN,MESABA AIRLINES,...,Take-off run,None,Small,Overcast,European starling,Y,0,0.0,0,No
25037,JOHN F KENNEDY INTL,< 1000 ft,CRJ-440,1,1,None,2011-10-16,No damage,NaN,PINNACLE,...,Landing Roll,None,Small,No Cloud,Short-eared owl,Y,0,0.0,0,No

In [55]:
filtered_data = bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'PA-31-350']
filtered_data

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
3804,FRIDAY HARBOR ARPT,< 1000 ft,PA-31-350,2 to 10,4,Other,2010-12-10,No damage,NaN,KENMORE AIR,...,Climb,None,Medium,Some Cloud,Unknown bird - medium,N,0,100.0,0,No
3861,KAPALUA ARPT,< 1000 ft,PA-31-350,2 to 10,10,None,2011-02-17,No damage,NaN,BUSINESS,...,Landing Roll,None,Small,Some Cloud,Common myna,Y,0,0.0,0,No
18803,MORRISTOWN MUNICIPAL ARPT,< 1000 ft,PA-31-350,1,1,None,2009-07-07,No damage,NaN,BUSINESS,...,Landing Roll,None,Small,No Cloud,American robin,Y,0,0.0,0,No
20527,TETERBORO AIRPORT,< 1000 ft,PA-31-350,1,1,None,2010-01-15,No damage,NaN,BUSINESS,...,Landing Roll,None,Small,Some Cloud,Mourning dove,Y,0,0.0,0,No
23406,KLAMATH FALLS INTL,< 1000 ft,PA-31-350,1,1,None,2011-04-20,Caused damage,NaN,AMERIFLIGHT,...,Approach,Rain,Large,Overcast,Greater white-fronted goose,N,0,100.0,0,No
25062,FORT LAUDERDALE EXECUTIVE ARPT,< 1000 ft,PA-31-350,1,1,None,2011-10-18,No damage,NaN,BUSINESS,...,Approach,None,Small,Overcast,American kestrel,N,0,20.0,0,No

In [56]:
filtered_data = bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'F/A-18']
filtered_data

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
25092,HONOLULU INTL ARPT,< 1000 ft,F/A-18,1,1,None,2011-10-22,No damage,NaN,HAWAIIAN AIR,...,Landing Roll,None,Small,No Cloud,Unknown bird - small,N,0,0.0,0,No

In [57]:
filtered_data = bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'DA-40']
filtered_data

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
25347,KALAELOA ARPT JOHN RODGERS FIELD,< 1000 ft,DA-40,1,1,None,2011-11-30,No damage,NaN,BUSINESS,...,Taxi,None,Small,No Cloud,Zebra dove,N,0,0.0,0,No

In [62]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'AT-38B']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
237,SHEPPARD AIR FORCE BASE,< 1000 ft,AT-38B,2 to 10,2,Precautionary Landing,2001-01-16,No damage,NaN,MILITARY,...,Climb,Rain,Medium,Some Cloud,Unknown bird or bat,Y,651,800.0,0,No
5132,SHEPPARD AIR FORCE BASE,> 1000 ft,AT-38B,1,1,None,2000-07-17,No damage,NaN,MILITARY,...,Approach,None,Medium,No Cloud,Unknown bird or bat,Y,21,1800.0,0,No
5139,SHEPPARD AIR FORCE BASE,< 1000 ft,AT-38B,1,1,None,2000-07-18,No damage,NaN,MILITARY,...,Take-off run,None,Small,No Cloud,Scissor-tailed flycatcher,Y,4267,0.0,0,No
5930,SHEPPARD AIR FORCE BASE,< 1000 ft,AT-38B,1,1,None,2001-04-18,No damage,NaN,MILITARY,...,Approach,None,Small,Some Cloud,Upland sandpiper,Y,0,200.0,0,No
6342,SHEPPARD AIR FORCE BASE,< 1000 ft,AT-38B,1,1,None,2001-08-15,No damage,NaN,MILITARY,...,Climb,None,Small,Some Cloud,Killdeer,Y,0,0.0,0,No
7757,SHEPPARD AIR FORCE BASE,< 1000 ft,AT-38B,1,1,None,2002-09-24,No damage,NaN,MILITARY,...,Take-off run,None,Small,No Cloud,Scissor-tailed flycatcher,Y,0,0.0,0,No
7831,SHEPPARD AIR FORCE BASE,< 1000 ft,AT-38B,1,1,None,2002-10-07,No damage,NaN,MILITARY,...,Take-off run,None,Small,Overcast,Killdeer,Y,0,0.0,0,No
7893,SHEPPARD AIR FORCE BASE,> 1000 ft,AT-38B,1,1,None,2002-10-21,No damage,NaN,MILITARY,...,Approach,None,Medium,No Cloud,Unknown bird or bat,Y,0,1300.0,0,No

In [63]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'C-130E']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
474,EGLIN AFB/NW FLORIDA REGIONAL ARPT,< 1000 ft,C-130E,2 to 10,9,None,2002-02-01,No damage,NaN,MILITARY,...,Climb,Snow,Medium,Overcast,Unknown bird or bat,Y,0,150.0,0,No

In [64]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'A-10A']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
477,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,A-10A,2 to 10,4,Precautionary Landing,2002-02-07,No damage,NaN,MILITARY,...,Climb,None,Small,No Cloud,Cedar waxwing,Y,0,340.0,0,No
6104,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,A-10A,1,1,Precautionary Landing,2001-06-20,No damage,NaN,MILITARY,...,Climb,None,Medium,No Cloud,Unknown bird or bat,Y,0,10.0,0,No
6774,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,A-10A,1,1,None,2002-02-04,No damage,NaN,MILITARY,...,Approach,None,Medium,Some Cloud,Unknown bird or bat,Y,0,300.0,0,No
7067,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,A-10A,1,1,None,2002-05-13,No damage,NaN,MILITARY,...,Parked,None,Medium,Some Cloud,Unknown bird or bat,Y,0,0.0,0,No
7190,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,A-10A,1,1,None,2002-06-08,No damage,NaN,MILITARY,...,Climb,None,Medium,Some Cloud,Unknown bird or bat,Y,0,5.0,0,No

In [67]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'MISC - OTHER']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
2264,LORAIN COUNTY REGIONAL ARPT,< 1000 ft,MISC - OTHER,2 to 10,10,None,2007-09-09,No damage,NaN,PRIVATELY OWNED,...,Approach,None,Small,Some Cloud,Mourning dove,Y,0,25.0,0,No

In [68]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'F-16D']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
568,EGLIN AFB/NW FLORIDA REGIONAL ARPT,< 1000 ft,F-16D,2 to 10,5,None,2002-07-15,No damage,NaN,MILITARY,...,Take-off run,None,Small,No Cloud,Mourning dove,Y,0,0.0,0,No

In [69]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'CESSNA UNKN']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
2421,GRAND FORKS INTL,> 1000 ft,CESSNA UNKN,2 to 10,10,None,2008-02-03,Caused damage,NaN,PRIVATELY OWNED,...,Descent,Snow,Medium,Some Cloud,Unknown bird - medium,N,487,2200.0,0,No
5282,WILL ROGERS WORLD ARPT,< 1000 ft,CESSNA UNKN,1,1,None,2000-08-17,No damage,NaN,UNKNOWN,...,Approach,None,Small,Some Cloud,Rock pigeon,N,0,300.0,0,No
5316,LINCOLN MUNICIPAL,< 1000 ft,CESSNA UNKN,1,1,None,2000-08-25,No damage,NaN,UNKNOWN,...,Approach,None,Small,No Cloud,Unknown bird - small,N,0,50.0,0,No
9823,WICHITA MID-CONTINENT ARPT,< 1000 ft,CESSNA UNKN,1,1,None,2004-06-29,No damage,NaN,BUSINESS,...,Approach,None,Small,Some Cloud,Unknown bird - small,N,0,500.0,0,No

In [70]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'CITATION MUSTANG 510']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
2796,JOE FOSS FIELD ARPT,< 1000 ft,CITATION MUSTANG 510,2 to 10,4,Precautionary Landing,2009-03-10,Caused damage,NaN,BUSINESS,...,Climb,Snow,Large,Overcast,Snow goose,N,31624,500.0,0,No
19707,HOUSTON-HOBBY,< 1000 ft,CITATION MUSTANG 510,1,1,None,2009-09-17,No damage,NaN,BUSINESS,...,Approach,None,Small,Some Cloud,Unknown bird - small,N,369,200.0,0,No
21541,OAKLAND COUNTY INTL,< 1000 ft,CITATION MUSTANG 510,1,1,None,2010-07-14,No damage,NaN,BUSINESS,...,Approach,None,Small,Some Cloud,Unknown bird - small,N,0,10.0,0,No
21584,BOB HOPE ARPT,< 1000 ft,CITATION MUSTANG 510,1,1,None,2010-07-19,No damage,NaN,BUSINESS,...,Climb,None,Small,Overcast,Unknown bird - small,N,0,100.0,0,No
21909,HAGERSTOWN REGIONAL,< 1000 ft,CITATION MUSTANG 510,1,1,None,2010-08-13,No damage,NaN,BUSINESS,...,Landing Roll,None,Small,Overcast,American kestrel,N,0,0.0,0,No

In [71]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'C-21A']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
306,CHARLESTON AFB/INTL ARPT,< 1000 ft,C-21A,2 to 10,5,Aborted Take-off,2001-07-07,No damage,NaN,MILITARY,...,Climb,None,Medium,No Cloud,Unknown bird or bat,Y,0,0.0,0,No
307,CHARLESTON AFB/INTL ARPT,< 1000 ft,C-21A,2 to 10,2,Aborted Take-off,2001-07-07,No damage,NaN,MILITARY,...,Take-off run,None,Medium,Some Cloud,Unknown bird or bat,Y,0,0.0,0,No

In [73]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'HAWKER 900']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
3489,COLUMBUS MUNICIPAL ARPT (IN),< 1000 ft,HAWKER 900,2 to 10,3,None,2010-07-27,No damage,NaN,BUSINESS,...,Climb,None,Small,No Cloud,Blackbirds,N,0,15.0,0,No
20398,SARASOTA-BRADENTON,< 1000 ft,HAWKER 900,1,1,Precautionary Landing,2009-12-06,Caused damage,NaN,BUSINESS,...,Climb,None,Large,No Cloud,Turkey vulture,N,10578,40.0,0,No

In [75]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'BD-700']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
3629,ST LOUIS DOWNTOWN,< 1000 ft,BD-700,2 to 10,8,Aborted Take-off,2010-09-08,No damage,NaN,BUSINESS,...,Take-off run,None,Medium,Some Cloud,Unknown bird - medium,N,0,0.0,0,No
19683,WESTCHESTER COUNTY ARPT,< 1000 ft,BD-700,1,1,None,2009-09-16,No damage,NaN,BUSINESS,...,Landing Roll,None,Small,Overcast,Unknown bird - small,Y,0,0.0,0,No
21411,ATLANTIC CITY INTL,< 1000 ft,BD-700,1,1,None,2010-07-01,No damage,NaN,GOVERNMENT,...,Approach,None,Small,Some Cloud,Laughing gull,Y,0,30.0,0,No
22807,WASHINGTON DULLES INTL ARPT,> 1000 ft,BD-700,1,1,None,2010-11-02,Caused damage,NaN,BUSINESS,...,Approach,None,Medium,No Cloud,Unknown bird - medium,N,266945,2500.0,0,No

In [76]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'B-787-800']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
4013,KLAMATH FALLS INTL,< 1000 ft,B-787-800,2 to 10,4,None,2011-07-22,No damage,NaN,BOEING COMMERCIAL AIRPLANE GRP,...,Approach,None,Medium,No Cloud,California gull,N,0,100.0,0,No

In [78]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'HU-25']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
4208,CAPE COD COAST GUARD AIR STATION,< 1000 ft,HU-25,2 to 10,6,Precautionary Landing,2011-10-05,No damage,NaN,GOVERNMENT,...,Take-off run,None,Small,Some Cloud,Black-bellied plover,N,0,0.0,0,No
19064,HOMESTEAD AIR RESERVE BASE,< 1000 ft,HU-25,1,1,Other,2009-07-27,No damage,NaN,GOVERNMENT,...,Approach,None,Medium,Some Cloud,Unknown bird - medium,N,0,75.0,0,No
22468,HOMESTEAD AIR RESERVE BASE,< 1000 ft,HU-25,1,1,None,2010-09-30,No damage,NaN,GOVERNMENT,...,Approach,None,Small,No Cloud,Unknown bird - small,N,0,200.0,0,No

In [79]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'HOMEBUILT']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
4402,TEHACHAPI MUNICIPAL ARPT,> 1000 ft,HOMEBUILT,11 to 100,93,None,2003-01-27,Caused damage,NaN,PRIVATELY OWNED,...,Descent,None,Medium,No Cloud,American wigeon,N,2297,1500.0,0,No
15940,KENDALL-TAMIAMI EXECUTIVE ARPT,> 1000 ft,HOMEBUILT,1,1,Precautionary Landing,2008-01-26,Caused damage,NaN,PRIVATELY OWNED,...,Climb,None,Large,No Cloud,Turkey vulture,Y,866,1500.0,0,No
16487,METRO OAKLAND INTL,< 1000 ft,HOMEBUILT,1,1,None,2008-06-14,No damage,NaN,PRIVATELY OWNED,...,Landing Roll,None,Small,No Cloud,European starling,Y,0,0.0,0,No

In [80]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'F-15E']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
4667,EGLIN AFB/NW FLORIDA REGIONAL ARPT,< 1000 ft,F-15E,1,1,Precautionary Landing,2000-01-25,Caused damage,NaN,MILITARY,...,Climb,None,Large,No Cloud,Turkey vulture,Y,32827,400.0,0,No

In [81]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'KC-135R']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
4960,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,KC-135R,1,1,Precautionary Landing,2000-05-24,No damage,NaN,MILITARY,...,Take-off run,None,Medium,No Cloud,Unknown bird or bat,Y,0,0.0,0,No
5821,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,KC-135R,1,1,Precautionary Landing,2001-02-23,No damage,NaN,MILITARY,...,Approach,None,Medium,No Cloud,Red-tailed hawk,Y,32540,1000.0,0,No
7830,CHARLESTON AFB/INTL ARPT,< 1000 ft,KC-135R,1,1,None,2002-10-07,No damage,NaN,MILITARY,...,Approach,None,Medium,No Cloud,Unknown bird or bat,Y,0,500.0,0,No
7892,EGLIN AFB/NW FLORIDA REGIONAL ARPT,< 1000 ft,KC-135R,1,1,Precautionary Landing,2002-10-21,No damage,NaN,MILITARY,...,Take-off run,None,Medium,Some Cloud,Unknown bird or bat,Y,0,4.0,0,No

In [87]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'GRUMMAN']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
5196,HEMET-RYAN ARPT,< 1000 ft,GRUMMAN,1,1,None,2000-07-31,Caused damage,NaN,GOVERNMENT,...,Take-off run,None,Medium,No Cloud,Red-tailed hawk,N,8018,0.0,0,No

In [90]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == "MC-130H"]

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
5733,EGLIN AFB/NW FLORIDA REGIONAL ARPT,< 1000 ft,MC-130H,1,1,None,2000-11-27,No damage,NaN,MILITARY,...,Approach,None,Medium,No Cloud,Unknown bird or bat,Y,0,1000.0,0,No

In [93]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'KC-135R']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
4960,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,KC-135R,1,1,Precautionary Landing,2000-05-24,No damage,NaN,MILITARY,...,Take-off run,None,Medium,No Cloud,Unknown bird or bat,Y,0,0.0,0,No
5821,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,KC-135R,1,1,Precautionary Landing,2001-02-23,No damage,NaN,MILITARY,...,Approach,None,Medium,No Cloud,Red-tailed hawk,Y,32540,1000.0,0,No
7830,CHARLESTON AFB/INTL ARPT,< 1000 ft,KC-135R,1,1,None,2002-10-07,No damage,NaN,MILITARY,...,Approach,None,Medium,No Cloud,Unknown bird or bat,Y,0,500.0,0,No
7892,EGLIN AFB/NW FLORIDA REGIONAL ARPT,< 1000 ft,KC-135R,1,1,Precautionary Landing,2002-10-21,No damage,NaN,MILITARY,...,Take-off run,None,Medium,Some Cloud,Unknown bird or bat,Y,0,4.0,0,No

In [104]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'F-16C']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
7250,EGLIN AFB/NW FLORIDA REGIONAL ARPT,< 1000 ft,F-16C,1,1,None,2002-06-24,No damage,NaN,MILITARY,...,Approach,None,Medium,Some Cloud,Unknown bird or bat,Y,0,500.0,0,No

In [106]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'T-1A']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
7368,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,T-1A,1,1,None,2002-07-20,No damage,NaN,MILITARY,...,Approach,None,Small,No Cloud,Barn swallow,Y,0,100.0,0,No

In [108]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'F-15C']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
7525,EGLIN AFB/NW FLORIDA REGIONAL ARPT,< 1000 ft,F-15C,1,1,None,2002-08-13,No damage,NaN,MILITARY,...,Take-off run,None,Small,No Cloud,Cliff swallow,Y,0,10.0,0,No

In [109]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'E-8C']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
7644,BARKSDALE AIR FORCE BASE ARPT,< 1000 ft,E-8C,1,1,Precautionary Landing,2002-09-04,No damage,NaN,MILITARY,...,Climb,None,Small,No Cloud,Common nighthawk,Y,0,1000.0,0,No

In [115]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'CANADAIR']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
8497,DALLAS/FORT WORTH INTL ARPT,< 1000 ft,CANADAIR,1,1,Aborted Take-off,2003-06-21,No damage,NaN,ATLANTIC SOUTHEAST,...,Take-off run,None,Small,Some Cloud,Mourning dove,N,0,0.0,0,No

In [117]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'CL-215']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
11853,VAN NUYS ARPT,< 1000 ft,CL-215,1,1,None,2005-10-01,No damage,NaN,GOVERNMENT,...,Landing Roll,None,Medium,Overcast,American coot,N,0,0.0,0,No

In [145]:


# Sample DataFrame


# Define specific rows and column
rows_to_fill = [3540,3666, 13814,14726,14918,15631,16001,16457, 21427,21520]
column_to_fill = 'Aircraft: Number of engines?'

# Isolate the subset
subset = bird_strike2.loc[rows_to_fill, column_to_fill]

In [146]:
filled_subset = subset.bfill()

In [149]:
filled_subset 
bird_strike2.loc[rows_to_fill, column_to_fill] = filled_subset

In [150]:
bird_strike2.isnull().sum()

Airport: Name                           0
Altitude bin                            0
Aircraft: Make/Model                    0
Wildlife: Number struck                 0
Wildlife: Number Struck Actual          0
Effect: Impact to flight                0
FlightDate                              0
Effect: Indicated Damage                0
Aircraft: Number of engines?          227
Aircraft: Airline/Operator              0
Origin State                          449
When: Phase of flight                   0
Conditions: Precipitation               0
Wildlife: Size                          0
Conditions: Sky                         0
Wildlife: Species                       0
Pilot warned of birds or wildlife?      0
Cost: Total $                           0
Feet above ground                       0
Number of people injured                0
Is Aircraft Large?                      0
dtype: int64

In [156]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'AMD ALARUS CH2000']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
12932,LONG ISLAND MAC ARTHUR,< 1000 ft,AMD ALARUS CH2000,1,1,None,2006-07-13,No damage,NaN,BUSINESS,...,Landing Roll,None,Small,Overcast,Unknown bird - small,N,0,0.0,0,No

In [163]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'ECLIPSE 500']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
17504,GROTON-NEW LONDON AR,< 1000 ft,ECLIPSE 500,1,1,None,2008-10-26,No damage,NaN,PRIVATELY OWNED,...,Approach,None,Medium,Some Cloud,Unknown bird - medium,Y,0,500.0,0,No
17693,LOUISVILLE INTL ARPT,< 1000 ft,ECLIPSE 500,1,1,None,2008-12-06,No damage,NaN,BUSINESS,...,Approach,None,Small,No Cloud,Rock pigeon,N,0,1000.0,0,No
18482,CHICAGO EXECUTIVE ARPT,> 1000 ft,ECLIPSE 500,1,1,None,2009-05-26,Caused damage,NaN,BUSINESS,...,Descent,Rain,Medium,Overcast,Unknown bird - medium,N,0,1800.0,0,No
19375,BIRMINGHAM-SHUTTLESWORTH INTL,< 1000 ft,ECLIPSE 500,1,1,None,2009-08-21,No damage,NaN,BUSINESS,...,Landing Roll,None,Small,No Cloud,Unknown bird - small,N,0,0.0,0,No
22659,UNIVERSITY PARK ARPT,< 1000 ft,ECLIPSE 500,1,1,None,2010-10-18,Caused damage,NaN,BUSINESS,...,Climb,None,Medium,Some Cloud,Mallard,N,46202,300.0,0,No

In [165]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'CESSNA LC-41']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
17940,TETERBORO AIRPORT,< 1000 ft,CESSNA LC-41,1,1,Aborted Take-off,2009-03-07,No damage,NaN,BUSINESS,...,Take-off run,None,Large,No Cloud,Canada goose,Y,0,0.0,0,No

In [167]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'SA227 DC METRO 23']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
17960,SANTA MARIA PUBLIC,< 1000 ft,SA227 DC METRO 23,1,1,None,2009-03-13,No damage,NaN,AMERIFLIGHT,...,Approach,None,Small,No Cloud,Unknown bird - small,N,0,200.0,0,No
18747,ONTARIO INTL ARPT,< 1000 ft,SA227 DC METRO 23,1,1,None,2009-06-30,No damage,NaN,AMERIFLIGHT,...,Landing Roll,None,Small,Some Cloud,American kestrel,Y,0,0.0,0,No

In [172]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'GRUMMAN S-2 TRACKER']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
19048,NEVADA COUNTY AIR PARK,< 1000 ft,GRUMMAN S-2 TRACKER,1,1,None,2009-07-25,Caused damage,NaN,BUSINESS,...,Approach,None,Small,No Cloud,Killdeer,N,263533,320.0,0,No
24125,UKIAH MUNICIPAL ARPT,< 1000 ft,GRUMMAN S-2 TRACKER,1,1,None,2011-07-22,No damage,NaN,GOVERNMENT,...,Take-off run,None,Small,No Cloud,Unknown bird - small,N,0,0.0,0,No

In [180]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'HC-130']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
20706,MC CLELLAN AIRFIELD,< 1000 ft,HC-130,1,1,None,2010-03-17,Caused damage,NaN,GOVERNMENT,...,Approach,None,Small,No Cloud,Unknown bird - small,N,0,10.0,0,No

In [181]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'T-38N']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
20876,ELLINGTON FIELD ARPT,> 1000 ft,T-38N,1,1,None,2010-04-22,No damage,NaN,GOVERNMENT,...,Approach,None,Small,Some Cloud,Unknown bird - small,N,0,1600.0,0,No

In [186]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'T-38']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
22280,ELLINGTON FIELD ARPT,< 1000 ft,T-38,1,1,None,2010-09-14,No damage,NaN,GOVERNMENT,...,Take-off run,None,Small,Some Cloud,Unknown bird - small,N,0,0.0,0,No
22781,ELLINGTON FIELD ARPT,< 1000 ft,T-38,1,1,None,2010-11-01,No damage,NaN,GOVERNMENT,...,Take-off run,None,Medium,Some Cloud,Broad-winged hawk,N,0,0.0,0,No
23971,ELLINGTON FIELD ARPT,< 1000 ft,T-38,1,1,None,2011-07-06,No damage,NaN,GOVERNMENT,...,Take-off run,None,Small,No Cloud,Killdeer,Y,0,0.0,0,No
24725,ELLINGTON FIELD ARPT,< 1000 ft,T-38,1,1,None,2011-09-18,No damage,NaN,GOVERNMENT,...,Landing Roll,None,Small,No Cloud,Perching birds (y),N,0,0.0,0,No

In [187]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'B-737-600']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
22387,MCCARREN INTL,< 1000 ft,B-737-600,1,1,None,2010-09-23,No damage,NaN,BUSINESS,...,Climb,None,Small,No Cloud,Unknown bird - small,N,0,300.0,0,Yes
23774,LOS ANGELES INTL,< 1000 ft,B-737-600,1,1,None,2011-06-10,No damage,NaN,WESTJET,...,Take-off run,None,Medium,Overcast,Peregrine falcon,N,0,0.0,0,Yes

In [190]:
rows_to_fill2 = [3574, 23032]
column_to_fill2 = 'Aircraft: Number of engines?'

subset2 = bird_strike2.loc[rows_to_fill2, column_to_fill2]

filled_subset2 = subset2.ffill()

bird_strike2.loc[rows_to_fill2, column_to_fill2] = filled_subset2

In [192]:
bird_strike2.isnull().sum()

Airport: Name                           0
Altitude bin                            0
Aircraft: Make/Model                    0
Wildlife: Number struck                 0
Wildlife: Number Struck Actual          0
Effect: Impact to flight                0
FlightDate                              0
Effect: Indicated Damage                0
Aircraft: Number of engines?          226
Aircraft: Airline/Operator              0
Origin State                          449
When: Phase of flight                   0
Conditions: Precipitation               0
Wildlife: Size                          0
Conditions: Sky                         0
Wildlife: Species                       0
Pilot warned of birds or wildlife?      0
Cost: Total $                           0
Feet above ground                       0
Number of people injured                0
Is Aircraft Large?                      0
dtype: int64

In [195]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'A-23 MUSKATEER']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
23189,STILLWATER REGIONAL ARPT,< 1000 ft,A-23 MUSKATEER,1,1,Other,2011-03-10,Caused damage,NaN,PRIVATELY OWNED,...,Landing Roll,None,Large,No Cloud,White-tailed deer,N,1500,0.0,0,No

In [197]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'LOCKHEED P3A']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
23237,DANIEL ODUBER QUIROS INTL,< 1000 ft,LOCKHEED P3A,1,1,None,2011-03-21,No damage,NaN,US CUSTOMS AND BORDER PROTECTION,...,Approach,None,Small,Some Cloud,Unknown bird - small,N,0,500.0,0,No

In [199]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'CRJ-900']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
23241,SANTA BARBARA MUNICIPAL,< 1000 ft,CRJ-900,1,1,None,2011-03-22,No damage,NaN,MESA AIRLINES,...,Approach,None,Medium,No Cloud,Western gull,Y,0,30.0,0,No

In [201]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'FLIGHT DESIGN CTSW']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
23649,LORAIN COUNTY REGIONAL ARPT,> 1000 ft,FLIGHT DESIGN CTSW,1,1,Precautionary Landing,2011-05-22,No damage,NaN,BUSINESS,...,Approach,None,Small,No Cloud,Unknown bird - small,N,0,2400.0,0,No

In [202]:
bird_strike2[bird_strike2['Aircraft: Make/Model'] == 'CL-RJ705']

,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
23714,LOGAN INTL,< 1000 ft,CL-RJ705,1,1,None,2011-05-31,No damage,NaN,AIR CANADA JAZZ,...,Climb,None,Small,No Cloud,Killdeer,Y,0,10.0,0,No

In [208]:
bird_strike2.isnull().sum()

Airport: Name                           0
Altitude bin                            0
Aircraft: Make/Model                    0
Wildlife: Number struck                 0
Wildlife: Number Struck Actual          0
Effect: Impact to flight                0
FlightDate                              0
Effect: Indicated Damage                0
Aircraft: Number of engines?          226
Aircraft: Airline/Operator              0
Origin State                          449
When: Phase of flight                   0
Conditions: Precipitation               0
Wildlife: Size                          0
Conditions: Sky                         0
Wildlife: Species                       0
Pilot warned of birds or wildlife?      0
Cost: Total $                           0
Feet above ground                       0
Number of people injured                0
Is Aircraft Large?                      0
dtype: int64

In [209]:
bird_strike2.to_csv(r"D:\UM internship\Bird Strike\Bird_strike2.csv")

In [210]:
bird_strike2['Aircraft: Number of engines?'].unique()

array([ 2.,  3.,  4., nan,  1.])

In [7]:
bird_strike2.iloc[3574:,:]

,Unnamed: 0,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,...,When: Phase of flight,Conditions: Precipitation,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
3574,3576,COLORADO SPRINGS MUNICIPAL,< 1000 ft,B-747-8 SERIES,2 to 10,4,None,2010-08-21,No damage,4.0,...,Landing Roll,None,Small,No Cloud,Sparrows,N,0,0.0,0,No
3575,3577,LOVELL FIELD ARPT,< 1000 ft,EMB-145,2 to 10,10,None,2010-08-21,No damage,2.0,...,Take-off run,None,Small,Some Cloud,Mourning dove,Y,0,0.0,0,No
3576,3578,JACKSON EVERS INTL,< 1000 ft,A-319,2 to 10,3,None,2010-08-21,No damage,2.0,...,Landing Roll,None,Small,Some Cloud,Swallows,Y,0,0.0,0,No
3577,3579,SAN FRANCISCO INTL ARPT,< 1000 ft,CL-RJ700,2 to 10,10,None,2010-08-21,No damage,2.0,...,Landing Roll,None,Small,Some Cloud,Western sandpiper,N,0,0.0,0,No
3578,3580,PORT COLUMBUS INTL,> 1000 ft,MD-82,2 to 10,3,None,2010-08-21,Caused damage,2.0,...,Approach,None,Large,No Cloud,Unknown bird - large,N,0,1500.0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25424,25552,SACRAMENTO INTL,< 1000 ft,B-737-700,1,1,None,2011-12-29,No damage,2.0,...,Approach,None,Medium,No Cloud,Mallard,Y,0,10.0,0,Yes
25425,25553,REDDING MUNICIPAL,> 1000 ft,EMB-120,1,1,None,2011-12-30,No damage,2.0,...,Approach,Fog,Large,Overcast,Unknown bird - large,N,0,1500.0,0,No
25426,25554,ORLANDO INTL,< 1000 ft,A-321,1,1,None,2011-12-30,No damage,2.0,...,Landing Roll,None,Small,Some Cloud,Tree swallow,Y,0,0.0,0,No
25427,25556,DETROIT METRO WAYNE COUNTY ARPT,< 1000 ft,B-757-200,1,1,None,2011-12-31,No damage,2.0,...,Landing Roll,None,Medium,Some Cloud,Unknown bird - medium,Y,0,0.0,0,Yes
25428,25557,ABRAHAM LINCOLN CAPITAL ARPT,< 1000 ft,B-737-400,1,1,None,2011-12-31,Caused damage,2.0,...,Take-off run,None,Medium,No Cloud,Red-tailed hawk,N,0,0.0,0,Yes